module.exports = {
  content: ["./app.vue", "./{components,pages,layouts}/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: { extend: { boxShadow: { panel: "0 18px 50px -32px rgba(15, 23, 42, 0.3)" } } },
  daisyui: {
    themes: [
      {
        catalog: {
          primary: "#4f46e5",
          "primary-content": "#ffffff",
          secondary: "#e0e7ff",
          "secondary-content": "#312e81",
          accent: "#0891b2",
          "accent-content": "#ffffff",
          neutral: "#172033",
          "neutral-content": "#f8fafc",
          "base-100": "#ffffff",
          "base-200": "#f8fafc",
          "base-300": "#e9eef5",
          "base-content": "#182235",
          info: "#0284c7",
          success: "#059669",
          warning: "#d97706",
          error: "#dc2626",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.8rem",
          "--animation-btn": "0.15s",
        },
      },
      {
        "catalog-dark": {
          primary: "#818cf8",
          "primary-content": "#111827",
          secondary: "#28345a",
          "secondary-content": "#e0e7ff",
          accent: "#22d3ee",
          "accent-content": "#083344",
          neutral: "#080d18",
          "neutral-content": "#f8fafc",
          "base-100": "#111827",
          "base-200": "#0f172a",
          "base-300": "#1e293b",
          "base-content": "#e5edf7",
          info: "#38bdf8",
          success: "#34d399",
          warning: "#fbbf24",
          error: "#fb7185",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.8rem",
          "--animation-btn": "0.15s",
        },
      },
    ],
  },
  variants: { extend: {} },
  plugins: [require("@tailwindcss/aspect-ratio"), require("@tailwindcss/typography"), require("daisyui")],
};
