
# Build Nuxt
FROM node:20-alpine AS frontend-builder
WORKDIR  /app
RUN corepack enable && corepack prepare pnpm@8.15.9 --activate
COPY frontend/package.json frontend/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --shamefully-hoist
COPY frontend .
RUN pnpm build

# Build API
FROM golang:1.24-alpine AS builder
ARG BUILD_TIME
ARG COMMIT
ARG VERSION
RUN apk update && \
    apk upgrade && \
    apk add --update git build-base gcc g++

WORKDIR /go/src/app
COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download
COPY ./backend .
RUN rm -rf ./app/api/public
COPY --from=frontend-builder /app/.output/public ./app/api/static/public
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags "-s -w -X main.commit=$COMMIT -X main.buildTime=$BUILD_TIME -X main.version=$VERSION"  \
    -o /go/bin/api \
    -v ./app/api/*.go && \
    chmod +x /go/bin/api && \
    # create a directory so that we can copy it in the next stage
    mkdir /data

# Production Stage
FROM gcr.io/distroless/static

ENV CATALOG_MODE=production
ENV CATALOG_STORAGE_DATA=/data/
ENV CATALOG_STORAGE_SQLITE_URL=/data/catalog.db?_fk=1

# Copy the binary and the (empty) /data dir and
# change the ownership to the low-privileged user
COPY --from=builder --chown=nonroot /go/bin/api /app
COPY --from=builder --chown=nonroot /data /data

LABEL Name=catalog Version=0.0.1
LABEL org.opencontainers.image.source="https://github.com/sdmad737/catalog"
EXPOSE 7745
VOLUME [ "/data" ]

# Drop root and run as low-privileged user
USER nonroot
ENTRYPOINT [ "/app" ]
CMD [ "/data/config.yml" ]
