// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/checkout"
	"github.com/sdmad737/catalog/backend/internal/data/ent/group"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/person"
)

// Checkout is the model entity for the Checkout schema.
type Checkout struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CheckedOutAt holds the value of the "checked_out_at" field.
	CheckedOutAt time.Time `json:"checked_out_at,omitempty"`
	// DueAt holds the value of the "due_at" field.
	DueAt *time.Time `json:"due_at,omitempty"`
	// ReturnedAt holds the value of the "returned_at" field.
	ReturnedAt *time.Time `json:"returned_at,omitempty"`
	// ConditionOut holds the value of the "condition_out" field.
	ConditionOut checkout.ConditionOut `json:"condition_out,omitempty"`
	// ConditionIn holds the value of the "condition_in" field.
	ConditionIn checkout.ConditionIn `json:"condition_in,omitempty"`
	// CheckoutNote holds the value of the "checkout_note" field.
	CheckoutNote string `json:"checkout_note,omitempty"`
	// ReturnNote holds the value of the "return_note" field.
	ReturnNote string `json:"return_note,omitempty"`
	// CheckedOutBy holds the value of the "checked_out_by" field.
	CheckedOutBy string `json:"checked_out_by,omitempty"`
	// ReturnedBy holds the value of the "returned_by" field.
	ReturnedBy string `json:"returned_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckoutQuery when eager-loading is set.
	Edges            CheckoutEdges `json:"edges"`
	group_checkouts  *uuid.UUID
	item_checkouts   *uuid.UUID
	person_checkouts *uuid.UUID
	selectValues     sql.SelectValues
}

// CheckoutEdges holds the relations/edges for other nodes in the graph.
type CheckoutEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// Person holds the value of the person edge.
	Person *Person `json:"person,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckoutEdges) GroupOrErr() (*Group, error) {
	if e.loadedTypes[0] {
		if e.Group == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: group.Label}
		}
		return e.Group, nil
	}
	return nil, &NotLoadedError{edge: "group"}
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckoutEdges) ItemOrErr() (*Item, error) {
	if e.loadedTypes[1] {
		if e.Item == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: item.Label}
		}
		return e.Item, nil
	}
	return nil, &NotLoadedError{edge: "item"}
}

// PersonOrErr returns the Person value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckoutEdges) PersonOrErr() (*Person, error) {
	if e.loadedTypes[2] {
		if e.Person == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: person.Label}
		}
		return e.Person, nil
	}
	return nil, &NotLoadedError{edge: "person"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Checkout) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkout.FieldConditionOut, checkout.FieldConditionIn, checkout.FieldCheckoutNote, checkout.FieldReturnNote, checkout.FieldCheckedOutBy, checkout.FieldReturnedBy:
			values[i] = new(sql.NullString)
		case checkout.FieldCreatedAt, checkout.FieldUpdatedAt, checkout.FieldCheckedOutAt, checkout.FieldDueAt, checkout.FieldReturnedAt:
			values[i] = new(sql.NullTime)
		case checkout.FieldID:
			values[i] = new(uuid.UUID)
		case checkout.ForeignKeys[0]: // group_checkouts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case checkout.ForeignKeys[1]: // item_checkouts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case checkout.ForeignKeys[2]: // person_checkouts
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Checkout fields.
func (c *Checkout) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkout.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				c.ID = *value
			}
		case checkout.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case checkout.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		case checkout.FieldCheckedOutAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_out_at", values[i])
			} else if value.Valid {
				c.CheckedOutAt = value.Time
			}
		case checkout.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				c.DueAt = new(time.Time)
				*c.DueAt = value.Time
			}
		case checkout.FieldReturnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field returned_at", values[i])
			} else if value.Valid {
				c.ReturnedAt = new(time.Time)
				*c.ReturnedAt = value.Time
			}
		case checkout.FieldConditionOut:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition_out", values[i])
			} else if value.Valid {
				c.ConditionOut = checkout.ConditionOut(value.String)
			}
		case checkout.FieldConditionIn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition_in", values[i])
			} else if value.Valid {
				c.ConditionIn = checkout.ConditionIn(value.String)
			}
		case checkout.FieldCheckoutNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_note", values[i])
			} else if value.Valid {
				c.CheckoutNote = value.String
			}
		case checkout.FieldReturnNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field return_note", values[i])
			} else if value.Valid {
				c.ReturnNote = value.String
			}
		case checkout.FieldCheckedOutBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checked_out_by", values[i])
			} else if value.Valid {
				c.CheckedOutBy = value.String
			}
		case checkout.FieldReturnedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field returned_by", values[i])
			} else if value.Valid {
				c.ReturnedBy = value.String
			}
		case checkout.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_checkouts", values[i])
			} else if value.Valid {
				c.group_checkouts = new(uuid.UUID)
				*c.group_checkouts = *value.S.(*uuid.UUID)
			}
		case checkout.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field item_checkouts", values[i])
			} else if value.Valid {
				c.item_checkouts = new(uuid.UUID)
				*c.item_checkouts = *value.S.(*uuid.UUID)
			}
		case checkout.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field person_checkouts", values[i])
			} else if value.Valid {
				c.person_checkouts = new(uuid.UUID)
				*c.person_checkouts = *value.S.(*uuid.UUID)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Checkout.
// This includes values selected through modifiers, order, etc.
func (c *Checkout) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Checkout entity.
func (c *Checkout) QueryGroup() *GroupQuery {
	return NewCheckoutClient(c.config).QueryGroup(c)
}

// QueryItem queries the "item" edge of the Checkout entity.
func (c *Checkout) QueryItem() *ItemQuery {
	return NewCheckoutClient(c.config).QueryItem(c)
}

// QueryPerson queries the "person" edge of the Checkout entity.
func (c *Checkout) QueryPerson() *PersonQuery {
	return NewCheckoutClient(c.config).QueryPerson(c)
}

// Update returns a builder for updating this Checkout.
// Note that you need to call Checkout.Unwrap() before calling this method if this Checkout
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Checkout) Update() *CheckoutUpdateOne {
	return NewCheckoutClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Checkout entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Checkout) Unwrap() *Checkout {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Checkout is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Checkout) String() string {
	var builder strings.Builder
	builder.WriteString("Checkout(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("checked_out_at=")
	builder.WriteString(c.CheckedOutAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := c.DueAt; v != nil {
		builder.WriteString("due_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := c.ReturnedAt; v != nil {
		builder.WriteString("returned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("condition_out=")
	builder.WriteString(fmt.Sprintf("%v", c.ConditionOut))
	builder.WriteString(", ")
	builder.WriteString("condition_in=")
	builder.WriteString(fmt.Sprintf("%v", c.ConditionIn))
	builder.WriteString(", ")
	builder.WriteString("checkout_note=")
	builder.WriteString(c.CheckoutNote)
	builder.WriteString(", ")
	builder.WriteString("return_note=")
	builder.WriteString(c.ReturnNote)
	builder.WriteString(", ")
	builder.WriteString("checked_out_by=")
	builder.WriteString(c.CheckedOutBy)
	builder.WriteString(", ")
	builder.WriteString("returned_by=")
	builder.WriteString(c.ReturnedBy)
	builder.WriteByte(')')
	return builder.String()
}

// Checkouts is a parsable slice of Checkout.
type Checkouts []*Checkout
