// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/checkout"
	"github.com/sdmad737/catalog/backend/internal/data/ent/group"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/person"
)

// CheckoutCreate is the builder for creating a Checkout entity.
type CheckoutCreate struct {
	config
	mutation *CheckoutMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cc *CheckoutCreate) SetCreatedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCreatedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CheckoutCreate) SetUpdatedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableUpdatedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (cc *CheckoutCreate) SetCheckedOutAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetCheckedOutAt(t)
	return cc
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCheckedOutAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetCheckedOutAt(*t)
	}
	return cc
}

// SetDueAt sets the "due_at" field.
func (cc *CheckoutCreate) SetDueAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetDueAt(t)
	return cc
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableDueAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetDueAt(*t)
	}
	return cc
}

// SetReturnedAt sets the "returned_at" field.
func (cc *CheckoutCreate) SetReturnedAt(t time.Time) *CheckoutCreate {
	cc.mutation.SetReturnedAt(t)
	return cc
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableReturnedAt(t *time.Time) *CheckoutCreate {
	if t != nil {
		cc.SetReturnedAt(*t)
	}
	return cc
}

// SetConditionOut sets the "condition_out" field.
func (cc *CheckoutCreate) SetConditionOut(co checkout.ConditionOut) *CheckoutCreate {
	cc.mutation.SetConditionOut(co)
	return cc
}

// SetNillableConditionOut sets the "condition_out" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableConditionOut(co *checkout.ConditionOut) *CheckoutCreate {
	if co != nil {
		cc.SetConditionOut(*co)
	}
	return cc
}

// SetConditionIn sets the "condition_in" field.
func (cc *CheckoutCreate) SetConditionIn(ci checkout.ConditionIn) *CheckoutCreate {
	cc.mutation.SetConditionIn(ci)
	return cc
}

// SetNillableConditionIn sets the "condition_in" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableConditionIn(ci *checkout.ConditionIn) *CheckoutCreate {
	if ci != nil {
		cc.SetConditionIn(*ci)
	}
	return cc
}

// SetCheckoutNote sets the "checkout_note" field.
func (cc *CheckoutCreate) SetCheckoutNote(s string) *CheckoutCreate {
	cc.mutation.SetCheckoutNote(s)
	return cc
}

// SetNillableCheckoutNote sets the "checkout_note" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCheckoutNote(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCheckoutNote(*s)
	}
	return cc
}

// SetReturnNote sets the "return_note" field.
func (cc *CheckoutCreate) SetReturnNote(s string) *CheckoutCreate {
	cc.mutation.SetReturnNote(s)
	return cc
}

// SetNillableReturnNote sets the "return_note" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableReturnNote(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetReturnNote(*s)
	}
	return cc
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (cc *CheckoutCreate) SetCheckedOutBy(s string) *CheckoutCreate {
	cc.mutation.SetCheckedOutBy(s)
	return cc
}

// SetNillableCheckedOutBy sets the "checked_out_by" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableCheckedOutBy(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetCheckedOutBy(*s)
	}
	return cc
}

// SetReturnedBy sets the "returned_by" field.
func (cc *CheckoutCreate) SetReturnedBy(s string) *CheckoutCreate {
	cc.mutation.SetReturnedBy(s)
	return cc
}

// SetNillableReturnedBy sets the "returned_by" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableReturnedBy(s *string) *CheckoutCreate {
	if s != nil {
		cc.SetReturnedBy(*s)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CheckoutCreate) SetID(u uuid.UUID) *CheckoutCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *CheckoutCreate) SetNillableID(u *uuid.UUID) *CheckoutCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (cc *CheckoutCreate) SetGroupID(id uuid.UUID) *CheckoutCreate {
	cc.mutation.SetGroupID(id)
	return cc
}

// SetGroup sets the "group" edge to the Group entity.
func (cc *CheckoutCreate) SetGroup(g *Group) *CheckoutCreate {
	return cc.SetGroupID(g.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (cc *CheckoutCreate) SetItemID(id uuid.UUID) *CheckoutCreate {
	cc.mutation.SetItemID(id)
	return cc
}

// SetItem sets the "item" edge to the Item entity.
func (cc *CheckoutCreate) SetItem(i *Item) *CheckoutCreate {
	return cc.SetItemID(i.ID)
}

// SetPersonID sets the "person" edge to the Person entity by ID.
func (cc *CheckoutCreate) SetPersonID(id uuid.UUID) *CheckoutCreate {
	cc.mutation.SetPersonID(id)
	return cc
}

// SetPerson sets the "person" edge to the Person entity.
func (cc *CheckoutCreate) SetPerson(p *Person) *CheckoutCreate {
	return cc.SetPersonID(p.ID)
}

// Mutation returns the CheckoutMutation object of the builder.
func (cc *CheckoutCreate) Mutation() *CheckoutMutation {
	return cc.mutation
}

// Save creates the Checkout in the database.
func (cc *CheckoutCreate) Save(ctx context.Context) (*Checkout, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CheckoutCreate) SaveX(ctx context.Context) *Checkout {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CheckoutCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CheckoutCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CheckoutCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := checkout.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := checkout.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.CheckedOutAt(); !ok {
		v := checkout.DefaultCheckedOutAt()
		cc.mutation.SetCheckedOutAt(v)
	}
	if _, ok := cc.mutation.ConditionOut(); !ok {
		v := checkout.DefaultConditionOut
		cc.mutation.SetConditionOut(v)
	}
	if _, ok := cc.mutation.ConditionIn(); !ok {
		v := checkout.DefaultConditionIn
		cc.mutation.SetConditionIn(v)
	}
	if _, ok := cc.mutation.ID(); !ok {
		v := checkout.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CheckoutCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Checkout.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Checkout.updated_at"`)}
	}
	if _, ok := cc.mutation.CheckedOutAt(); !ok {
		return &ValidationError{Name: "checked_out_at", err: errors.New(`ent: missing required field "Checkout.checked_out_at"`)}
	}
	if _, ok := cc.mutation.ConditionOut(); !ok {
		return &ValidationError{Name: "condition_out", err: errors.New(`ent: missing required field "Checkout.condition_out"`)}
	}
	if v, ok := cc.mutation.ConditionOut(); ok {
		if err := checkout.ConditionOutValidator(v); err != nil {
			return &ValidationError{Name: "condition_out", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_out": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ConditionIn(); !ok {
		return &ValidationError{Name: "condition_in", err: errors.New(`ent: missing required field "Checkout.condition_in"`)}
	}
	if v, ok := cc.mutation.ConditionIn(); ok {
		if err := checkout.ConditionInValidator(v); err != nil {
			return &ValidationError{Name: "condition_in", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_in": %w`, err)}
		}
	}
	if v, ok := cc.mutation.CheckoutNote(); ok {
		if err := checkout.CheckoutNoteValidator(v); err != nil {
			return &ValidationError{Name: "checkout_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_note": %w`, err)}
		}
	}
	if v, ok := cc.mutation.ReturnNote(); ok {
		if err := checkout.ReturnNoteValidator(v); err != nil {
			return &ValidationError{Name: "return_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.return_note": %w`, err)}
		}
	}
	if v, ok := cc.mutation.CheckedOutBy(); ok {
		if err := checkout.CheckedOutByValidator(v); err != nil {
			return &ValidationError{Name: "checked_out_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.checked_out_by": %w`, err)}
		}
	}
	if v, ok := cc.mutation.ReturnedBy(); ok {
		if err := checkout.ReturnedByValidator(v); err != nil {
			return &ValidationError{Name: "returned_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.returned_by": %w`, err)}
		}
	}
	if _, ok := cc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Checkout.group"`)}
	}
	if _, ok := cc.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "Checkout.item"`)}
	}
	if _, ok := cc.mutation.PersonID(); !ok {
		return &ValidationError{Name: "person", err: errors.New(`ent: missing required edge "Checkout.person"`)}
	}
	return nil
}

func (cc *CheckoutCreate) sqlSave(ctx context.Context) (*Checkout, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CheckoutCreate) createSpec() (*Checkout, *sqlgraph.CreateSpec) {
	var (
		_node = &Checkout{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(checkout.Table, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(checkout.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.CheckedOutAt(); ok {
		_spec.SetField(checkout.FieldCheckedOutAt, field.TypeTime, value)
		_node.CheckedOutAt = value
	}
	if value, ok := cc.mutation.DueAt(); ok {
		_spec.SetField(checkout.FieldDueAt, field.TypeTime, value)
		_node.DueAt = &value
	}
	if value, ok := cc.mutation.ReturnedAt(); ok {
		_spec.SetField(checkout.FieldReturnedAt, field.TypeTime, value)
		_node.ReturnedAt = &value
	}
	if value, ok := cc.mutation.ConditionOut(); ok {
		_spec.SetField(checkout.FieldConditionOut, field.TypeEnum, value)
		_node.ConditionOut = value
	}
	if value, ok := cc.mutation.ConditionIn(); ok {
		_spec.SetField(checkout.FieldConditionIn, field.TypeEnum, value)
		_node.ConditionIn = value
	}
	if value, ok := cc.mutation.CheckoutNote(); ok {
		_spec.SetField(checkout.FieldCheckoutNote, field.TypeString, value)
		_node.CheckoutNote = value
	}
	if value, ok := cc.mutation.ReturnNote(); ok {
		_spec.SetField(checkout.FieldReturnNote, field.TypeString, value)
		_node.ReturnNote = value
	}
	if value, ok := cc.mutation.CheckedOutBy(); ok {
		_spec.SetField(checkout.FieldCheckedOutBy, field.TypeString, value)
		_node.CheckedOutBy = value
	}
	if value, ok := cc.mutation.ReturnedBy(); ok {
		_spec.SetField(checkout.FieldReturnedBy, field.TypeString, value)
		_node.ReturnedBy = value
	}
	if nodes := cc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.GroupTable,
			Columns: []string{checkout.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_checkouts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.ItemTable,
			Columns: []string{checkout.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_checkouts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.PersonTable,
			Columns: []string{checkout.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.person_checkouts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheckoutCreateBulk is the builder for creating many Checkout entities in bulk.
type CheckoutCreateBulk struct {
	config
	err      error
	builders []*CheckoutCreate
}

// Save creates the Checkout entities in the database.
func (ccb *CheckoutCreateBulk) Save(ctx context.Context) ([]*Checkout, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Checkout, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckoutMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CheckoutCreateBulk) SaveX(ctx context.Context) []*Checkout {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CheckoutCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CheckoutCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
