// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/checkout"
	"github.com/sdmad737/catalog/backend/internal/data/ent/group"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/person"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// CheckoutQuery is the builder for querying Checkout entities.
type CheckoutQuery struct {
	config
	ctx        *QueryContext
	order      []checkout.OrderOption
	inters     []Interceptor
	predicates []predicate.Checkout
	withGroup  *GroupQuery
	withItem   *ItemQuery
	withPerson *PersonQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CheckoutQuery builder.
func (cq *CheckoutQuery) Where(ps ...predicate.Checkout) *CheckoutQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CheckoutQuery) Limit(limit int) *CheckoutQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CheckoutQuery) Offset(offset int) *CheckoutQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CheckoutQuery) Unique(unique bool) *CheckoutQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CheckoutQuery) Order(o ...checkout.OrderOption) *CheckoutQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryGroup chains the current query on the "group" edge.
func (cq *CheckoutQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checkout.Table, checkout.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkout.GroupTable, checkout.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItem chains the current query on the "item" edge.
func (cq *CheckoutQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checkout.Table, checkout.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkout.ItemTable, checkout.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPerson chains the current query on the "person" edge.
func (cq *CheckoutQuery) QueryPerson() *PersonQuery {
	query := (&PersonClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(checkout.Table, checkout.FieldID, selector),
			sqlgraph.To(person.Table, person.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkout.PersonTable, checkout.PersonColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Checkout entity from the query.
// Returns a *NotFoundError when no Checkout was found.
func (cq *CheckoutQuery) First(ctx context.Context) (*Checkout, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{checkout.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CheckoutQuery) FirstX(ctx context.Context) *Checkout {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Checkout ID from the query.
// Returns a *NotFoundError when no Checkout ID was found.
func (cq *CheckoutQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{checkout.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CheckoutQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Checkout entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Checkout entity is found.
// Returns a *NotFoundError when no Checkout entities are found.
func (cq *CheckoutQuery) Only(ctx context.Context) (*Checkout, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{checkout.Label}
	default:
		return nil, &NotSingularError{checkout.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CheckoutQuery) OnlyX(ctx context.Context) *Checkout {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Checkout ID in the query.
// Returns a *NotSingularError when more than one Checkout ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CheckoutQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{checkout.Label}
	default:
		err = &NotSingularError{checkout.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CheckoutQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Checkouts.
func (cq *CheckoutQuery) All(ctx context.Context) ([]*Checkout, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Checkout, *CheckoutQuery]()
	return withInterceptors[[]*Checkout](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CheckoutQuery) AllX(ctx context.Context) []*Checkout {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Checkout IDs.
func (cq *CheckoutQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(checkout.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CheckoutQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CheckoutQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CheckoutQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CheckoutQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CheckoutQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CheckoutQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CheckoutQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CheckoutQuery) Clone() *CheckoutQuery {
	if cq == nil {
		return nil
	}
	return &CheckoutQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]checkout.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Checkout{}, cq.predicates...),
		withGroup:  cq.withGroup.Clone(),
		withItem:   cq.withItem.Clone(),
		withPerson: cq.withPerson.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CheckoutQuery) WithGroup(opts ...func(*GroupQuery)) *CheckoutQuery {
	query := (&GroupClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withGroup = query
	return cq
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CheckoutQuery) WithItem(opts ...func(*ItemQuery)) *CheckoutQuery {
	query := (&ItemClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withItem = query
	return cq
}

// WithPerson tells the query-builder to eager-load the nodes that are connected to
// the "person" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CheckoutQuery) WithPerson(opts ...func(*PersonQuery)) *CheckoutQuery {
	query := (&PersonClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withPerson = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Checkout.Query().
//		GroupBy(checkout.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CheckoutQuery) GroupBy(field string, fields ...string) *CheckoutGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CheckoutGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = checkout.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Checkout.Query().
//		Select(checkout.FieldCreatedAt).
//		Scan(ctx, &v)
func (cq *CheckoutQuery) Select(fields ...string) *CheckoutSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CheckoutSelect{CheckoutQuery: cq}
	sbuild.label = checkout.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CheckoutSelect configured with the given aggregations.
func (cq *CheckoutQuery) Aggregate(fns ...AggregateFunc) *CheckoutSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CheckoutQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !checkout.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CheckoutQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Checkout, error) {
	var (
		nodes       = []*Checkout{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [3]bool{
			cq.withGroup != nil,
			cq.withItem != nil,
			cq.withPerson != nil,
		}
	)
	if cq.withGroup != nil || cq.withItem != nil || cq.withPerson != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, checkout.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Checkout).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Checkout{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withGroup; query != nil {
		if err := cq.loadGroup(ctx, query, nodes, nil,
			func(n *Checkout, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withItem; query != nil {
		if err := cq.loadItem(ctx, query, nodes, nil,
			func(n *Checkout, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withPerson; query != nil {
		if err := cq.loadPerson(ctx, query, nodes, nil,
			func(n *Checkout, e *Person) { n.Edges.Person = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CheckoutQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*Checkout, init func(*Checkout), assign func(*Checkout, *Group)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Checkout)
	for i := range nodes {
		if nodes[i].group_checkouts == nil {
			continue
		}
		fk := *nodes[i].group_checkouts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_checkouts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CheckoutQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*Checkout, init func(*Checkout), assign func(*Checkout, *Item)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Checkout)
	for i := range nodes {
		if nodes[i].item_checkouts == nil {
			continue
		}
		fk := *nodes[i].item_checkouts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_checkouts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CheckoutQuery) loadPerson(ctx context.Context, query *PersonQuery, nodes []*Checkout, init func(*Checkout), assign func(*Checkout, *Person)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Checkout)
	for i := range nodes {
		if nodes[i].person_checkouts == nil {
			continue
		}
		fk := *nodes[i].person_checkouts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(person.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "person_checkouts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cq *CheckoutQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CheckoutQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(checkout.Table, checkout.Columns, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkout.FieldID)
		for i := range fields {
			if fields[i] != checkout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CheckoutQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(checkout.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = checkout.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CheckoutGroupBy is the group-by builder for Checkout entities.
type CheckoutGroupBy struct {
	selector
	build *CheckoutQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CheckoutGroupBy) Aggregate(fns ...AggregateFunc) *CheckoutGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CheckoutGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckoutQuery, *CheckoutGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CheckoutGroupBy) sqlScan(ctx context.Context, root *CheckoutQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CheckoutSelect is the builder for selecting fields of Checkout entities.
type CheckoutSelect struct {
	*CheckoutQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CheckoutSelect) Aggregate(fns ...AggregateFunc) *CheckoutSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CheckoutSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CheckoutQuery, *CheckoutSelect](ctx, cs.CheckoutQuery, cs, cs.inters, v)
}

func (cs *CheckoutSelect) sqlScan(ctx context.Context, root *CheckoutQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
