// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/checkout"
	"github.com/sdmad737/catalog/backend/internal/data/ent/group"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/person"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// CheckoutUpdate is the builder for updating Checkout entities.
type CheckoutUpdate struct {
	config
	hooks    []Hook
	mutation *CheckoutMutation
}

// Where appends a list predicates to the CheckoutUpdate builder.
func (cu *CheckoutUpdate) Where(ps ...predicate.Checkout) *CheckoutUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CheckoutUpdate) SetUpdatedAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (cu *CheckoutUpdate) SetCheckedOutAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetCheckedOutAt(t)
	return cu
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckedOutAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetCheckedOutAt(*t)
	}
	return cu
}

// SetDueAt sets the "due_at" field.
func (cu *CheckoutUpdate) SetDueAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetDueAt(t)
	return cu
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableDueAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetDueAt(*t)
	}
	return cu
}

// ClearDueAt clears the value of the "due_at" field.
func (cu *CheckoutUpdate) ClearDueAt() *CheckoutUpdate {
	cu.mutation.ClearDueAt()
	return cu
}

// SetReturnedAt sets the "returned_at" field.
func (cu *CheckoutUpdate) SetReturnedAt(t time.Time) *CheckoutUpdate {
	cu.mutation.SetReturnedAt(t)
	return cu
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableReturnedAt(t *time.Time) *CheckoutUpdate {
	if t != nil {
		cu.SetReturnedAt(*t)
	}
	return cu
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (cu *CheckoutUpdate) ClearReturnedAt() *CheckoutUpdate {
	cu.mutation.ClearReturnedAt()
	return cu
}

// SetConditionOut sets the "condition_out" field.
func (cu *CheckoutUpdate) SetConditionOut(co checkout.ConditionOut) *CheckoutUpdate {
	cu.mutation.SetConditionOut(co)
	return cu
}

// SetNillableConditionOut sets the "condition_out" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableConditionOut(co *checkout.ConditionOut) *CheckoutUpdate {
	if co != nil {
		cu.SetConditionOut(*co)
	}
	return cu
}

// SetConditionIn sets the "condition_in" field.
func (cu *CheckoutUpdate) SetConditionIn(ci checkout.ConditionIn) *CheckoutUpdate {
	cu.mutation.SetConditionIn(ci)
	return cu
}

// SetNillableConditionIn sets the "condition_in" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableConditionIn(ci *checkout.ConditionIn) *CheckoutUpdate {
	if ci != nil {
		cu.SetConditionIn(*ci)
	}
	return cu
}

// SetCheckoutNote sets the "checkout_note" field.
func (cu *CheckoutUpdate) SetCheckoutNote(s string) *CheckoutUpdate {
	cu.mutation.SetCheckoutNote(s)
	return cu
}

// SetNillableCheckoutNote sets the "checkout_note" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckoutNote(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCheckoutNote(*s)
	}
	return cu
}

// ClearCheckoutNote clears the value of the "checkout_note" field.
func (cu *CheckoutUpdate) ClearCheckoutNote() *CheckoutUpdate {
	cu.mutation.ClearCheckoutNote()
	return cu
}

// SetReturnNote sets the "return_note" field.
func (cu *CheckoutUpdate) SetReturnNote(s string) *CheckoutUpdate {
	cu.mutation.SetReturnNote(s)
	return cu
}

// SetNillableReturnNote sets the "return_note" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableReturnNote(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetReturnNote(*s)
	}
	return cu
}

// ClearReturnNote clears the value of the "return_note" field.
func (cu *CheckoutUpdate) ClearReturnNote() *CheckoutUpdate {
	cu.mutation.ClearReturnNote()
	return cu
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (cu *CheckoutUpdate) SetCheckedOutBy(s string) *CheckoutUpdate {
	cu.mutation.SetCheckedOutBy(s)
	return cu
}

// SetNillableCheckedOutBy sets the "checked_out_by" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableCheckedOutBy(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetCheckedOutBy(*s)
	}
	return cu
}

// ClearCheckedOutBy clears the value of the "checked_out_by" field.
func (cu *CheckoutUpdate) ClearCheckedOutBy() *CheckoutUpdate {
	cu.mutation.ClearCheckedOutBy()
	return cu
}

// SetReturnedBy sets the "returned_by" field.
func (cu *CheckoutUpdate) SetReturnedBy(s string) *CheckoutUpdate {
	cu.mutation.SetReturnedBy(s)
	return cu
}

// SetNillableReturnedBy sets the "returned_by" field if the given value is not nil.
func (cu *CheckoutUpdate) SetNillableReturnedBy(s *string) *CheckoutUpdate {
	if s != nil {
		cu.SetReturnedBy(*s)
	}
	return cu
}

// ClearReturnedBy clears the value of the "returned_by" field.
func (cu *CheckoutUpdate) ClearReturnedBy() *CheckoutUpdate {
	cu.mutation.ClearReturnedBy()
	return cu
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (cu *CheckoutUpdate) SetGroupID(id uuid.UUID) *CheckoutUpdate {
	cu.mutation.SetGroupID(id)
	return cu
}

// SetGroup sets the "group" edge to the Group entity.
func (cu *CheckoutUpdate) SetGroup(g *Group) *CheckoutUpdate {
	return cu.SetGroupID(g.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (cu *CheckoutUpdate) SetItemID(id uuid.UUID) *CheckoutUpdate {
	cu.mutation.SetItemID(id)
	return cu
}

// SetItem sets the "item" edge to the Item entity.
func (cu *CheckoutUpdate) SetItem(i *Item) *CheckoutUpdate {
	return cu.SetItemID(i.ID)
}

// SetPersonID sets the "person" edge to the Person entity by ID.
func (cu *CheckoutUpdate) SetPersonID(id uuid.UUID) *CheckoutUpdate {
	cu.mutation.SetPersonID(id)
	return cu
}

// SetPerson sets the "person" edge to the Person entity.
func (cu *CheckoutUpdate) SetPerson(p *Person) *CheckoutUpdate {
	return cu.SetPersonID(p.ID)
}

// Mutation returns the CheckoutMutation object of the builder.
func (cu *CheckoutUpdate) Mutation() *CheckoutMutation {
	return cu.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (cu *CheckoutUpdate) ClearGroup() *CheckoutUpdate {
	cu.mutation.ClearGroup()
	return cu
}

// ClearItem clears the "item" edge to the Item entity.
func (cu *CheckoutUpdate) ClearItem() *CheckoutUpdate {
	cu.mutation.ClearItem()
	return cu
}

// ClearPerson clears the "person" edge to the Person entity.
func (cu *CheckoutUpdate) ClearPerson() *CheckoutUpdate {
	cu.mutation.ClearPerson()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CheckoutUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CheckoutUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CheckoutUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CheckoutUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CheckoutUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := checkout.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CheckoutUpdate) check() error {
	if v, ok := cu.mutation.ConditionOut(); ok {
		if err := checkout.ConditionOutValidator(v); err != nil {
			return &ValidationError{Name: "condition_out", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_out": %w`, err)}
		}
	}
	if v, ok := cu.mutation.ConditionIn(); ok {
		if err := checkout.ConditionInValidator(v); err != nil {
			return &ValidationError{Name: "condition_in", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_in": %w`, err)}
		}
	}
	if v, ok := cu.mutation.CheckoutNote(); ok {
		if err := checkout.CheckoutNoteValidator(v); err != nil {
			return &ValidationError{Name: "checkout_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_note": %w`, err)}
		}
	}
	if v, ok := cu.mutation.ReturnNote(); ok {
		if err := checkout.ReturnNoteValidator(v); err != nil {
			return &ValidationError{Name: "return_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.return_note": %w`, err)}
		}
	}
	if v, ok := cu.mutation.CheckedOutBy(); ok {
		if err := checkout.CheckedOutByValidator(v); err != nil {
			return &ValidationError{Name: "checked_out_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.checked_out_by": %w`, err)}
		}
	}
	if v, ok := cu.mutation.ReturnedBy(); ok {
		if err := checkout.ReturnedByValidator(v); err != nil {
			return &ValidationError{Name: "returned_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.returned_by": %w`, err)}
		}
	}
	if _, ok := cu.mutation.GroupID(); cu.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.group"`)
	}
	if _, ok := cu.mutation.ItemID(); cu.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.item"`)
	}
	if _, ok := cu.mutation.PersonID(); cu.mutation.PersonCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.person"`)
	}
	return nil
}

func (cu *CheckoutUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkout.Table, checkout.Columns, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.CheckedOutAt(); ok {
		_spec.SetField(checkout.FieldCheckedOutAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.DueAt(); ok {
		_spec.SetField(checkout.FieldDueAt, field.TypeTime, value)
	}
	if cu.mutation.DueAtCleared() {
		_spec.ClearField(checkout.FieldDueAt, field.TypeTime)
	}
	if value, ok := cu.mutation.ReturnedAt(); ok {
		_spec.SetField(checkout.FieldReturnedAt, field.TypeTime, value)
	}
	if cu.mutation.ReturnedAtCleared() {
		_spec.ClearField(checkout.FieldReturnedAt, field.TypeTime)
	}
	if value, ok := cu.mutation.ConditionOut(); ok {
		_spec.SetField(checkout.FieldConditionOut, field.TypeEnum, value)
	}
	if value, ok := cu.mutation.ConditionIn(); ok {
		_spec.SetField(checkout.FieldConditionIn, field.TypeEnum, value)
	}
	if value, ok := cu.mutation.CheckoutNote(); ok {
		_spec.SetField(checkout.FieldCheckoutNote, field.TypeString, value)
	}
	if cu.mutation.CheckoutNoteCleared() {
		_spec.ClearField(checkout.FieldCheckoutNote, field.TypeString)
	}
	if value, ok := cu.mutation.ReturnNote(); ok {
		_spec.SetField(checkout.FieldReturnNote, field.TypeString, value)
	}
	if cu.mutation.ReturnNoteCleared() {
		_spec.ClearField(checkout.FieldReturnNote, field.TypeString)
	}
	if value, ok := cu.mutation.CheckedOutBy(); ok {
		_spec.SetField(checkout.FieldCheckedOutBy, field.TypeString, value)
	}
	if cu.mutation.CheckedOutByCleared() {
		_spec.ClearField(checkout.FieldCheckedOutBy, field.TypeString)
	}
	if value, ok := cu.mutation.ReturnedBy(); ok {
		_spec.SetField(checkout.FieldReturnedBy, field.TypeString, value)
	}
	if cu.mutation.ReturnedByCleared() {
		_spec.ClearField(checkout.FieldReturnedBy, field.TypeString)
	}
	if cu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.GroupTable,
			Columns: []string{checkout.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.GroupTable,
			Columns: []string{checkout.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.ItemTable,
			Columns: []string{checkout.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.ItemTable,
			Columns: []string{checkout.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.PersonTable,
			Columns: []string{checkout.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.PersonTable,
			Columns: []string{checkout.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CheckoutUpdateOne is the builder for updating a single Checkout entity.
type CheckoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckoutMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CheckoutUpdateOne) SetUpdatedAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (cuo *CheckoutUpdateOne) SetCheckedOutAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetCheckedOutAt(t)
	return cuo
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckedOutAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetCheckedOutAt(*t)
	}
	return cuo
}

// SetDueAt sets the "due_at" field.
func (cuo *CheckoutUpdateOne) SetDueAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetDueAt(t)
	return cuo
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableDueAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetDueAt(*t)
	}
	return cuo
}

// ClearDueAt clears the value of the "due_at" field.
func (cuo *CheckoutUpdateOne) ClearDueAt() *CheckoutUpdateOne {
	cuo.mutation.ClearDueAt()
	return cuo
}

// SetReturnedAt sets the "returned_at" field.
func (cuo *CheckoutUpdateOne) SetReturnedAt(t time.Time) *CheckoutUpdateOne {
	cuo.mutation.SetReturnedAt(t)
	return cuo
}

// SetNillableReturnedAt sets the "returned_at" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableReturnedAt(t *time.Time) *CheckoutUpdateOne {
	if t != nil {
		cuo.SetReturnedAt(*t)
	}
	return cuo
}

// ClearReturnedAt clears the value of the "returned_at" field.
func (cuo *CheckoutUpdateOne) ClearReturnedAt() *CheckoutUpdateOne {
	cuo.mutation.ClearReturnedAt()
	return cuo
}

// SetConditionOut sets the "condition_out" field.
func (cuo *CheckoutUpdateOne) SetConditionOut(co checkout.ConditionOut) *CheckoutUpdateOne {
	cuo.mutation.SetConditionOut(co)
	return cuo
}

// SetNillableConditionOut sets the "condition_out" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableConditionOut(co *checkout.ConditionOut) *CheckoutUpdateOne {
	if co != nil {
		cuo.SetConditionOut(*co)
	}
	return cuo
}

// SetConditionIn sets the "condition_in" field.
func (cuo *CheckoutUpdateOne) SetConditionIn(ci checkout.ConditionIn) *CheckoutUpdateOne {
	cuo.mutation.SetConditionIn(ci)
	return cuo
}

// SetNillableConditionIn sets the "condition_in" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableConditionIn(ci *checkout.ConditionIn) *CheckoutUpdateOne {
	if ci != nil {
		cuo.SetConditionIn(*ci)
	}
	return cuo
}

// SetCheckoutNote sets the "checkout_note" field.
func (cuo *CheckoutUpdateOne) SetCheckoutNote(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCheckoutNote(s)
	return cuo
}

// SetNillableCheckoutNote sets the "checkout_note" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckoutNote(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCheckoutNote(*s)
	}
	return cuo
}

// ClearCheckoutNote clears the value of the "checkout_note" field.
func (cuo *CheckoutUpdateOne) ClearCheckoutNote() *CheckoutUpdateOne {
	cuo.mutation.ClearCheckoutNote()
	return cuo
}

// SetReturnNote sets the "return_note" field.
func (cuo *CheckoutUpdateOne) SetReturnNote(s string) *CheckoutUpdateOne {
	cuo.mutation.SetReturnNote(s)
	return cuo
}

// SetNillableReturnNote sets the "return_note" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableReturnNote(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetReturnNote(*s)
	}
	return cuo
}

// ClearReturnNote clears the value of the "return_note" field.
func (cuo *CheckoutUpdateOne) ClearReturnNote() *CheckoutUpdateOne {
	cuo.mutation.ClearReturnNote()
	return cuo
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (cuo *CheckoutUpdateOne) SetCheckedOutBy(s string) *CheckoutUpdateOne {
	cuo.mutation.SetCheckedOutBy(s)
	return cuo
}

// SetNillableCheckedOutBy sets the "checked_out_by" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableCheckedOutBy(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetCheckedOutBy(*s)
	}
	return cuo
}

// ClearCheckedOutBy clears the value of the "checked_out_by" field.
func (cuo *CheckoutUpdateOne) ClearCheckedOutBy() *CheckoutUpdateOne {
	cuo.mutation.ClearCheckedOutBy()
	return cuo
}

// SetReturnedBy sets the "returned_by" field.
func (cuo *CheckoutUpdateOne) SetReturnedBy(s string) *CheckoutUpdateOne {
	cuo.mutation.SetReturnedBy(s)
	return cuo
}

// SetNillableReturnedBy sets the "returned_by" field if the given value is not nil.
func (cuo *CheckoutUpdateOne) SetNillableReturnedBy(s *string) *CheckoutUpdateOne {
	if s != nil {
		cuo.SetReturnedBy(*s)
	}
	return cuo
}

// ClearReturnedBy clears the value of the "returned_by" field.
func (cuo *CheckoutUpdateOne) ClearReturnedBy() *CheckoutUpdateOne {
	cuo.mutation.ClearReturnedBy()
	return cuo
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (cuo *CheckoutUpdateOne) SetGroupID(id uuid.UUID) *CheckoutUpdateOne {
	cuo.mutation.SetGroupID(id)
	return cuo
}

// SetGroup sets the "group" edge to the Group entity.
func (cuo *CheckoutUpdateOne) SetGroup(g *Group) *CheckoutUpdateOne {
	return cuo.SetGroupID(g.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (cuo *CheckoutUpdateOne) SetItemID(id uuid.UUID) *CheckoutUpdateOne {
	cuo.mutation.SetItemID(id)
	return cuo
}

// SetItem sets the "item" edge to the Item entity.
func (cuo *CheckoutUpdateOne) SetItem(i *Item) *CheckoutUpdateOne {
	return cuo.SetItemID(i.ID)
}

// SetPersonID sets the "person" edge to the Person entity by ID.
func (cuo *CheckoutUpdateOne) SetPersonID(id uuid.UUID) *CheckoutUpdateOne {
	cuo.mutation.SetPersonID(id)
	return cuo
}

// SetPerson sets the "person" edge to the Person entity.
func (cuo *CheckoutUpdateOne) SetPerson(p *Person) *CheckoutUpdateOne {
	return cuo.SetPersonID(p.ID)
}

// Mutation returns the CheckoutMutation object of the builder.
func (cuo *CheckoutUpdateOne) Mutation() *CheckoutMutation {
	return cuo.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (cuo *CheckoutUpdateOne) ClearGroup() *CheckoutUpdateOne {
	cuo.mutation.ClearGroup()
	return cuo
}

// ClearItem clears the "item" edge to the Item entity.
func (cuo *CheckoutUpdateOne) ClearItem() *CheckoutUpdateOne {
	cuo.mutation.ClearItem()
	return cuo
}

// ClearPerson clears the "person" edge to the Person entity.
func (cuo *CheckoutUpdateOne) ClearPerson() *CheckoutUpdateOne {
	cuo.mutation.ClearPerson()
	return cuo
}

// Where appends a list predicates to the CheckoutUpdate builder.
func (cuo *CheckoutUpdateOne) Where(ps ...predicate.Checkout) *CheckoutUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CheckoutUpdateOne) Select(field string, fields ...string) *CheckoutUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Checkout entity.
func (cuo *CheckoutUpdateOne) Save(ctx context.Context) (*Checkout, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CheckoutUpdateOne) SaveX(ctx context.Context) *Checkout {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CheckoutUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CheckoutUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CheckoutUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := checkout.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CheckoutUpdateOne) check() error {
	if v, ok := cuo.mutation.ConditionOut(); ok {
		if err := checkout.ConditionOutValidator(v); err != nil {
			return &ValidationError{Name: "condition_out", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_out": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.ConditionIn(); ok {
		if err := checkout.ConditionInValidator(v); err != nil {
			return &ValidationError{Name: "condition_in", err: fmt.Errorf(`ent: validator failed for field "Checkout.condition_in": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.CheckoutNote(); ok {
		if err := checkout.CheckoutNoteValidator(v); err != nil {
			return &ValidationError{Name: "checkout_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.checkout_note": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.ReturnNote(); ok {
		if err := checkout.ReturnNoteValidator(v); err != nil {
			return &ValidationError{Name: "return_note", err: fmt.Errorf(`ent: validator failed for field "Checkout.return_note": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.CheckedOutBy(); ok {
		if err := checkout.CheckedOutByValidator(v); err != nil {
			return &ValidationError{Name: "checked_out_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.checked_out_by": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.ReturnedBy(); ok {
		if err := checkout.ReturnedByValidator(v); err != nil {
			return &ValidationError{Name: "returned_by", err: fmt.Errorf(`ent: validator failed for field "Checkout.returned_by": %w`, err)}
		}
	}
	if _, ok := cuo.mutation.GroupID(); cuo.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.group"`)
	}
	if _, ok := cuo.mutation.ItemID(); cuo.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.item"`)
	}
	if _, ok := cuo.mutation.PersonID(); cuo.mutation.PersonCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Checkout.person"`)
	}
	return nil
}

func (cuo *CheckoutUpdateOne) sqlSave(ctx context.Context) (_node *Checkout, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkout.Table, checkout.Columns, sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Checkout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkout.FieldID)
		for _, f := range fields {
			if !checkout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(checkout.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.CheckedOutAt(); ok {
		_spec.SetField(checkout.FieldCheckedOutAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.DueAt(); ok {
		_spec.SetField(checkout.FieldDueAt, field.TypeTime, value)
	}
	if cuo.mutation.DueAtCleared() {
		_spec.ClearField(checkout.FieldDueAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.ReturnedAt(); ok {
		_spec.SetField(checkout.FieldReturnedAt, field.TypeTime, value)
	}
	if cuo.mutation.ReturnedAtCleared() {
		_spec.ClearField(checkout.FieldReturnedAt, field.TypeTime)
	}
	if value, ok := cuo.mutation.ConditionOut(); ok {
		_spec.SetField(checkout.FieldConditionOut, field.TypeEnum, value)
	}
	if value, ok := cuo.mutation.ConditionIn(); ok {
		_spec.SetField(checkout.FieldConditionIn, field.TypeEnum, value)
	}
	if value, ok := cuo.mutation.CheckoutNote(); ok {
		_spec.SetField(checkout.FieldCheckoutNote, field.TypeString, value)
	}
	if cuo.mutation.CheckoutNoteCleared() {
		_spec.ClearField(checkout.FieldCheckoutNote, field.TypeString)
	}
	if value, ok := cuo.mutation.ReturnNote(); ok {
		_spec.SetField(checkout.FieldReturnNote, field.TypeString, value)
	}
	if cuo.mutation.ReturnNoteCleared() {
		_spec.ClearField(checkout.FieldReturnNote, field.TypeString)
	}
	if value, ok := cuo.mutation.CheckedOutBy(); ok {
		_spec.SetField(checkout.FieldCheckedOutBy, field.TypeString, value)
	}
	if cuo.mutation.CheckedOutByCleared() {
		_spec.ClearField(checkout.FieldCheckedOutBy, field.TypeString)
	}
	if value, ok := cuo.mutation.ReturnedBy(); ok {
		_spec.SetField(checkout.FieldReturnedBy, field.TypeString, value)
	}
	if cuo.mutation.ReturnedByCleared() {
		_spec.ClearField(checkout.FieldReturnedBy, field.TypeString)
	}
	if cuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.GroupTable,
			Columns: []string{checkout.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.GroupTable,
			Columns: []string{checkout.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.ItemTable,
			Columns: []string{checkout.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.ItemTable,
			Columns: []string{checkout.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.PersonTable,
			Columns: []string{checkout.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkout.PersonTable,
			Columns: []string{checkout.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Checkout{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
