// Code generated by ent, DO NOT EDIT.

package ent

import "github.com/google/uuid"

func (a *Attachment) GetID() uuid.UUID {
	return a.ID
}

func (ar *AuthRoles) GetID() int {
	return ar.ID
}

func (at *AuthTokens) GetID() uuid.UUID {
	return at.ID
}

func (c *Checkout) GetID() uuid.UUID {
	return c.ID
}

func (d *Document) GetID() uuid.UUID {
	return d.ID
}

func (gr *Group) GetID() uuid.UUID {
	return gr.ID
}

func (git *GroupInvitationToken) GetID() uuid.UUID {
	return git.ID
}

func (i *Item) GetID() uuid.UUID {
	return i.ID
}

func (ie *ItemEvent) GetID() uuid.UUID {
	return ie.ID
}

func (_if *ItemField) GetID() uuid.UUID {
	return _if.ID
}

func (it *ItemTag) GetID() uuid.UUID {
	return it.ID
}

func (l *Label) GetID() uuid.UUID {
	return l.ID
}

func (l *Location) GetID() uuid.UUID {
	return l.ID
}

func (me *MaintenanceEntry) GetID() uuid.UUID {
	return me.ID
}

func (n *Notifier) GetID() uuid.UUID {
	return n.ID
}

func (pe *Person) GetID() uuid.UUID {
	return pe.ID
}

func (u *User) GetID() uuid.UUID {
	return u.ID
}
