// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemevent"
)

// ItemEvent is the model entity for the ItemEvent schema.
type ItemEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// ActorName holds the value of the "actor_name" field.
	ActorName string `json:"actor_name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemEventQuery when eager-loading is set.
	Edges        ItemEventEdges `json:"edges"`
	item_events  *uuid.UUID
	selectValues sql.SelectValues
}

// ItemEventEdges holds the relations/edges for other nodes in the graph.
type ItemEventEdges struct {
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEventEdges) ItemOrErr() (*Item, error) {
	if e.loadedTypes[0] {
		if e.Item == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: item.Label}
		}
		return e.Item, nil
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ItemEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case itemevent.FieldKind, itemevent.FieldSummary, itemevent.FieldNote, itemevent.FieldActorName:
			values[i] = new(sql.NullString)
		case itemevent.FieldCreatedAt, itemevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case itemevent.FieldID:
			values[i] = new(uuid.UUID)
		case itemevent.ForeignKeys[0]: // item_events
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ItemEvent fields.
func (ie *ItemEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case itemevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ie.ID = *value
			}
		case itemevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ie.CreatedAt = value.Time
			}
		case itemevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ie.UpdatedAt = value.Time
			}
		case itemevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				ie.Kind = value.String
			}
		case itemevent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				ie.Summary = value.String
			}
		case itemevent.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				ie.Note = value.String
			}
		case itemevent.FieldActorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_name", values[i])
			} else if value.Valid {
				ie.ActorName = value.String
			}
		case itemevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field item_events", values[i])
			} else if value.Valid {
				ie.item_events = new(uuid.UUID)
				*ie.item_events = *value.S.(*uuid.UUID)
			}
		default:
			ie.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ItemEvent.
// This includes values selected through modifiers, order, etc.
func (ie *ItemEvent) Value(name string) (ent.Value, error) {
	return ie.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the ItemEvent entity.
func (ie *ItemEvent) QueryItem() *ItemQuery {
	return NewItemEventClient(ie.config).QueryItem(ie)
}

// Update returns a builder for updating this ItemEvent.
// Note that you need to call ItemEvent.Unwrap() before calling this method if this ItemEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ie *ItemEvent) Update() *ItemEventUpdateOne {
	return NewItemEventClient(ie.config).UpdateOne(ie)
}

// Unwrap unwraps the ItemEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ie *ItemEvent) Unwrap() *ItemEvent {
	_tx, ok := ie.config.driver.(*txDriver)
	if !ok {
		panic("ent: ItemEvent is not a transactional entity")
	}
	ie.config.driver = _tx.drv
	return ie
}

// String implements the fmt.Stringer.
func (ie *ItemEvent) String() string {
	var builder strings.Builder
	builder.WriteString("ItemEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ie.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ie.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ie.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(ie.Kind)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(ie.Summary)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(ie.Note)
	builder.WriteString(", ")
	builder.WriteString("actor_name=")
	builder.WriteString(ie.ActorName)
	builder.WriteByte(')')
	return builder.String()
}

// ItemEvents is a parsable slice of ItemEvent.
type ItemEvents []*ItemEvent
