// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemtag"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemTagDelete is the builder for deleting a ItemTag entity.
type ItemTagDelete struct {
	config
	hooks    []Hook
	mutation *ItemTagMutation
}

// Where appends a list predicates to the ItemTagDelete builder.
func (itd *ItemTagDelete) Where(ps ...predicate.ItemTag) *ItemTagDelete {
	itd.mutation.Where(ps...)
	return itd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (itd *ItemTagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, itd.sqlExec, itd.mutation, itd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (itd *ItemTagDelete) ExecX(ctx context.Context) int {
	n, err := itd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (itd *ItemTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(itemtag.Table, sqlgraph.NewFieldSpec(itemtag.FieldID, field.TypeUUID))
	if ps := itd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, itd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	itd.mutation.done = true
	return affected, err
}

// ItemTagDeleteOne is the builder for deleting a single ItemTag entity.
type ItemTagDeleteOne struct {
	itd *ItemTagDelete
}

// Where appends a list predicates to the ItemTagDelete builder.
func (itdo *ItemTagDeleteOne) Where(ps ...predicate.ItemTag) *ItemTagDeleteOne {
	itdo.itd.mutation.Where(ps...)
	return itdo
}

// Exec executes the deletion query.
func (itdo *ItemTagDeleteOne) Exec(ctx context.Context) error {
	n, err := itdo.itd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemtag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (itdo *ItemTagDeleteOne) ExecX(ctx context.Context) {
	if err := itdo.Exec(ctx); err != nil {
		panic(err)
	}
}
