// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemtag"
)

// ItemTag is the model entity for the ItemTag schema.
type ItemTag struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublicToken holds the value of the "public_token" field.
	PublicToken string `json:"public_token,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// LastScannedAt holds the value of the "last_scanned_at" field.
	LastScannedAt *time.Time `json:"last_scanned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemTagQuery when eager-loading is set.
	Edges        ItemTagEdges `json:"edges"`
	item_tags    *uuid.UUID
	selectValues sql.SelectValues
}

// ItemTagEdges holds the relations/edges for other nodes in the graph.
type ItemTagEdges struct {
	// Item holds the value of the item edge.
	Item *Item `json:"item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemTagEdges) ItemOrErr() (*Item, error) {
	if e.loadedTypes[0] {
		if e.Item == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: item.Label}
		}
		return e.Item, nil
	}
	return nil, &NotLoadedError{edge: "item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ItemTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case itemtag.FieldPublicToken:
			values[i] = new(sql.NullString)
		case itemtag.FieldCreatedAt, itemtag.FieldUpdatedAt, itemtag.FieldRevokedAt, itemtag.FieldVerifiedAt, itemtag.FieldLastScannedAt:
			values[i] = new(sql.NullTime)
		case itemtag.FieldID:
			values[i] = new(uuid.UUID)
		case itemtag.ForeignKeys[0]: // item_tags
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ItemTag fields.
func (it *ItemTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case itemtag.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				it.ID = *value
			}
		case itemtag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				it.CreatedAt = value.Time
			}
		case itemtag.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				it.UpdatedAt = value.Time
			}
		case itemtag.FieldPublicToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_token", values[i])
			} else if value.Valid {
				it.PublicToken = value.String
			}
		case itemtag.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				it.RevokedAt = new(time.Time)
				*it.RevokedAt = value.Time
			}
		case itemtag.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				it.VerifiedAt = new(time.Time)
				*it.VerifiedAt = value.Time
			}
		case itemtag.FieldLastScannedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_scanned_at", values[i])
			} else if value.Valid {
				it.LastScannedAt = new(time.Time)
				*it.LastScannedAt = value.Time
			}
		case itemtag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field item_tags", values[i])
			} else if value.Valid {
				it.item_tags = new(uuid.UUID)
				*it.item_tags = *value.S.(*uuid.UUID)
			}
		default:
			it.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ItemTag.
// This includes values selected through modifiers, order, etc.
func (it *ItemTag) Value(name string) (ent.Value, error) {
	return it.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the ItemTag entity.
func (it *ItemTag) QueryItem() *ItemQuery {
	return NewItemTagClient(it.config).QueryItem(it)
}

// Update returns a builder for updating this ItemTag.
// Note that you need to call ItemTag.Unwrap() before calling this method if this ItemTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (it *ItemTag) Update() *ItemTagUpdateOne {
	return NewItemTagClient(it.config).UpdateOne(it)
}

// Unwrap unwraps the ItemTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (it *ItemTag) Unwrap() *ItemTag {
	_tx, ok := it.config.driver.(*txDriver)
	if !ok {
		panic("ent: ItemTag is not a transactional entity")
	}
	it.config.driver = _tx.drv
	return it
}

// String implements the fmt.Stringer.
func (it *ItemTag) String() string {
	var builder strings.Builder
	builder.WriteString("ItemTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", it.ID))
	builder.WriteString("created_at=")
	builder.WriteString(it.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(it.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("public_token=")
	builder.WriteString(it.PublicToken)
	builder.WriteString(", ")
	if v := it.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := it.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := it.LastScannedAt; v != nil {
		builder.WriteString("last_scanned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ItemTags is a parsable slice of ItemTag.
type ItemTags []*ItemTag
