// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemtag"
)

// ItemTagCreate is the builder for creating a ItemTag entity.
type ItemTagCreate struct {
	config
	mutation *ItemTagMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (itc *ItemTagCreate) SetCreatedAt(t time.Time) *ItemTagCreate {
	itc.mutation.SetCreatedAt(t)
	return itc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableCreatedAt(t *time.Time) *ItemTagCreate {
	if t != nil {
		itc.SetCreatedAt(*t)
	}
	return itc
}

// SetUpdatedAt sets the "updated_at" field.
func (itc *ItemTagCreate) SetUpdatedAt(t time.Time) *ItemTagCreate {
	itc.mutation.SetUpdatedAt(t)
	return itc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableUpdatedAt(t *time.Time) *ItemTagCreate {
	if t != nil {
		itc.SetUpdatedAt(*t)
	}
	return itc
}

// SetPublicToken sets the "public_token" field.
func (itc *ItemTagCreate) SetPublicToken(s string) *ItemTagCreate {
	itc.mutation.SetPublicToken(s)
	return itc
}

// SetRevokedAt sets the "revoked_at" field.
func (itc *ItemTagCreate) SetRevokedAt(t time.Time) *ItemTagCreate {
	itc.mutation.SetRevokedAt(t)
	return itc
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableRevokedAt(t *time.Time) *ItemTagCreate {
	if t != nil {
		itc.SetRevokedAt(*t)
	}
	return itc
}

// SetVerifiedAt sets the "verified_at" field.
func (itc *ItemTagCreate) SetVerifiedAt(t time.Time) *ItemTagCreate {
	itc.mutation.SetVerifiedAt(t)
	return itc
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableVerifiedAt(t *time.Time) *ItemTagCreate {
	if t != nil {
		itc.SetVerifiedAt(*t)
	}
	return itc
}

// SetLastScannedAt sets the "last_scanned_at" field.
func (itc *ItemTagCreate) SetLastScannedAt(t time.Time) *ItemTagCreate {
	itc.mutation.SetLastScannedAt(t)
	return itc
}

// SetNillableLastScannedAt sets the "last_scanned_at" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableLastScannedAt(t *time.Time) *ItemTagCreate {
	if t != nil {
		itc.SetLastScannedAt(*t)
	}
	return itc
}

// SetID sets the "id" field.
func (itc *ItemTagCreate) SetID(u uuid.UUID) *ItemTagCreate {
	itc.mutation.SetID(u)
	return itc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (itc *ItemTagCreate) SetNillableID(u *uuid.UUID) *ItemTagCreate {
	if u != nil {
		itc.SetID(*u)
	}
	return itc
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (itc *ItemTagCreate) SetItemID(id uuid.UUID) *ItemTagCreate {
	itc.mutation.SetItemID(id)
	return itc
}

// SetItem sets the "item" edge to the Item entity.
func (itc *ItemTagCreate) SetItem(i *Item) *ItemTagCreate {
	return itc.SetItemID(i.ID)
}

// Mutation returns the ItemTagMutation object of the builder.
func (itc *ItemTagCreate) Mutation() *ItemTagMutation {
	return itc.mutation
}

// Save creates the ItemTag in the database.
func (itc *ItemTagCreate) Save(ctx context.Context) (*ItemTag, error) {
	itc.defaults()
	return withHooks(ctx, itc.sqlSave, itc.mutation, itc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (itc *ItemTagCreate) SaveX(ctx context.Context) *ItemTag {
	v, err := itc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itc *ItemTagCreate) Exec(ctx context.Context) error {
	_, err := itc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itc *ItemTagCreate) ExecX(ctx context.Context) {
	if err := itc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (itc *ItemTagCreate) defaults() {
	if _, ok := itc.mutation.CreatedAt(); !ok {
		v := itemtag.DefaultCreatedAt()
		itc.mutation.SetCreatedAt(v)
	}
	if _, ok := itc.mutation.UpdatedAt(); !ok {
		v := itemtag.DefaultUpdatedAt()
		itc.mutation.SetUpdatedAt(v)
	}
	if _, ok := itc.mutation.ID(); !ok {
		v := itemtag.DefaultID()
		itc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itc *ItemTagCreate) check() error {
	if _, ok := itc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemTag.created_at"`)}
	}
	if _, ok := itc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemTag.updated_at"`)}
	}
	if _, ok := itc.mutation.PublicToken(); !ok {
		return &ValidationError{Name: "public_token", err: errors.New(`ent: missing required field "ItemTag.public_token"`)}
	}
	if v, ok := itc.mutation.PublicToken(); ok {
		if err := itemtag.PublicTokenValidator(v); err != nil {
			return &ValidationError{Name: "public_token", err: fmt.Errorf(`ent: validator failed for field "ItemTag.public_token": %w`, err)}
		}
	}
	if _, ok := itc.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ItemTag.item"`)}
	}
	return nil
}

func (itc *ItemTagCreate) sqlSave(ctx context.Context) (*ItemTag, error) {
	if err := itc.check(); err != nil {
		return nil, err
	}
	_node, _spec := itc.createSpec()
	if err := sqlgraph.CreateNode(ctx, itc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	itc.mutation.id = &_node.ID
	itc.mutation.done = true
	return _node, nil
}

func (itc *ItemTagCreate) createSpec() (*ItemTag, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemTag{config: itc.config}
		_spec = sqlgraph.NewCreateSpec(itemtag.Table, sqlgraph.NewFieldSpec(itemtag.FieldID, field.TypeUUID))
	)
	if id, ok := itc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := itc.mutation.CreatedAt(); ok {
		_spec.SetField(itemtag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := itc.mutation.UpdatedAt(); ok {
		_spec.SetField(itemtag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := itc.mutation.PublicToken(); ok {
		_spec.SetField(itemtag.FieldPublicToken, field.TypeString, value)
		_node.PublicToken = value
	}
	if value, ok := itc.mutation.RevokedAt(); ok {
		_spec.SetField(itemtag.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := itc.mutation.VerifiedAt(); ok {
		_spec.SetField(itemtag.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := itc.mutation.LastScannedAt(); ok {
		_spec.SetField(itemtag.FieldLastScannedAt, field.TypeTime, value)
		_node.LastScannedAt = &value
	}
	if nodes := itc.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtag.ItemTable,
			Columns: []string{itemtag.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_tags = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ItemTagCreateBulk is the builder for creating many ItemTag entities in bulk.
type ItemTagCreateBulk struct {
	config
	err      error
	builders []*ItemTagCreate
}

// Save creates the ItemTag entities in the database.
func (itcb *ItemTagCreateBulk) Save(ctx context.Context) ([]*ItemTag, error) {
	if itcb.err != nil {
		return nil, itcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(itcb.builders))
	nodes := make([]*ItemTag, len(itcb.builders))
	mutators := make([]Mutator, len(itcb.builders))
	for i := range itcb.builders {
		func(i int, root context.Context) {
			builder := itcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, itcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, itcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, itcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (itcb *ItemTagCreateBulk) SaveX(ctx context.Context) []*ItemTag {
	v, err := itcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (itcb *ItemTagCreateBulk) Exec(ctx context.Context) error {
	_, err := itcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itcb *ItemTagCreateBulk) ExecX(ctx context.Context) {
	if err := itcb.Exec(ctx); err != nil {
		panic(err)
	}
}
