// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemtag"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemTagUpdate is the builder for updating ItemTag entities.
type ItemTagUpdate struct {
	config
	hooks    []Hook
	mutation *ItemTagMutation
}

// Where appends a list predicates to the ItemTagUpdate builder.
func (itu *ItemTagUpdate) Where(ps ...predicate.ItemTag) *ItemTagUpdate {
	itu.mutation.Where(ps...)
	return itu
}

// SetUpdatedAt sets the "updated_at" field.
func (itu *ItemTagUpdate) SetUpdatedAt(t time.Time) *ItemTagUpdate {
	itu.mutation.SetUpdatedAt(t)
	return itu
}

// SetRevokedAt sets the "revoked_at" field.
func (itu *ItemTagUpdate) SetRevokedAt(t time.Time) *ItemTagUpdate {
	itu.mutation.SetRevokedAt(t)
	return itu
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (itu *ItemTagUpdate) SetNillableRevokedAt(t *time.Time) *ItemTagUpdate {
	if t != nil {
		itu.SetRevokedAt(*t)
	}
	return itu
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (itu *ItemTagUpdate) ClearRevokedAt() *ItemTagUpdate {
	itu.mutation.ClearRevokedAt()
	return itu
}

// SetVerifiedAt sets the "verified_at" field.
func (itu *ItemTagUpdate) SetVerifiedAt(t time.Time) *ItemTagUpdate {
	itu.mutation.SetVerifiedAt(t)
	return itu
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (itu *ItemTagUpdate) SetNillableVerifiedAt(t *time.Time) *ItemTagUpdate {
	if t != nil {
		itu.SetVerifiedAt(*t)
	}
	return itu
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (itu *ItemTagUpdate) ClearVerifiedAt() *ItemTagUpdate {
	itu.mutation.ClearVerifiedAt()
	return itu
}

// SetLastScannedAt sets the "last_scanned_at" field.
func (itu *ItemTagUpdate) SetLastScannedAt(t time.Time) *ItemTagUpdate {
	itu.mutation.SetLastScannedAt(t)
	return itu
}

// SetNillableLastScannedAt sets the "last_scanned_at" field if the given value is not nil.
func (itu *ItemTagUpdate) SetNillableLastScannedAt(t *time.Time) *ItemTagUpdate {
	if t != nil {
		itu.SetLastScannedAt(*t)
	}
	return itu
}

// ClearLastScannedAt clears the value of the "last_scanned_at" field.
func (itu *ItemTagUpdate) ClearLastScannedAt() *ItemTagUpdate {
	itu.mutation.ClearLastScannedAt()
	return itu
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (itu *ItemTagUpdate) SetItemID(id uuid.UUID) *ItemTagUpdate {
	itu.mutation.SetItemID(id)
	return itu
}

// SetItem sets the "item" edge to the Item entity.
func (itu *ItemTagUpdate) SetItem(i *Item) *ItemTagUpdate {
	return itu.SetItemID(i.ID)
}

// Mutation returns the ItemTagMutation object of the builder.
func (itu *ItemTagUpdate) Mutation() *ItemTagMutation {
	return itu.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (itu *ItemTagUpdate) ClearItem() *ItemTagUpdate {
	itu.mutation.ClearItem()
	return itu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (itu *ItemTagUpdate) Save(ctx context.Context) (int, error) {
	itu.defaults()
	return withHooks(ctx, itu.sqlSave, itu.mutation, itu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (itu *ItemTagUpdate) SaveX(ctx context.Context) int {
	affected, err := itu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (itu *ItemTagUpdate) Exec(ctx context.Context) error {
	_, err := itu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (itu *ItemTagUpdate) ExecX(ctx context.Context) {
	if err := itu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (itu *ItemTagUpdate) defaults() {
	if _, ok := itu.mutation.UpdatedAt(); !ok {
		v := itemtag.UpdateDefaultUpdatedAt()
		itu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (itu *ItemTagUpdate) check() error {
	if _, ok := itu.mutation.ItemID(); itu.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ItemTag.item"`)
	}
	return nil
}

func (itu *ItemTagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := itu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemtag.Table, itemtag.Columns, sqlgraph.NewFieldSpec(itemtag.FieldID, field.TypeUUID))
	if ps := itu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := itu.mutation.UpdatedAt(); ok {
		_spec.SetField(itemtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := itu.mutation.RevokedAt(); ok {
		_spec.SetField(itemtag.FieldRevokedAt, field.TypeTime, value)
	}
	if itu.mutation.RevokedAtCleared() {
		_spec.ClearField(itemtag.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := itu.mutation.VerifiedAt(); ok {
		_spec.SetField(itemtag.FieldVerifiedAt, field.TypeTime, value)
	}
	if itu.mutation.VerifiedAtCleared() {
		_spec.ClearField(itemtag.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := itu.mutation.LastScannedAt(); ok {
		_spec.SetField(itemtag.FieldLastScannedAt, field.TypeTime, value)
	}
	if itu.mutation.LastScannedAtCleared() {
		_spec.ClearField(itemtag.FieldLastScannedAt, field.TypeTime)
	}
	if itu.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtag.ItemTable,
			Columns: []string{itemtag.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := itu.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtag.ItemTable,
			Columns: []string{itemtag.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, itu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	itu.mutation.done = true
	return n, nil
}

// ItemTagUpdateOne is the builder for updating a single ItemTag entity.
type ItemTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemTagMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ituo *ItemTagUpdateOne) SetUpdatedAt(t time.Time) *ItemTagUpdateOne {
	ituo.mutation.SetUpdatedAt(t)
	return ituo
}

// SetRevokedAt sets the "revoked_at" field.
func (ituo *ItemTagUpdateOne) SetRevokedAt(t time.Time) *ItemTagUpdateOne {
	ituo.mutation.SetRevokedAt(t)
	return ituo
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (ituo *ItemTagUpdateOne) SetNillableRevokedAt(t *time.Time) *ItemTagUpdateOne {
	if t != nil {
		ituo.SetRevokedAt(*t)
	}
	return ituo
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (ituo *ItemTagUpdateOne) ClearRevokedAt() *ItemTagUpdateOne {
	ituo.mutation.ClearRevokedAt()
	return ituo
}

// SetVerifiedAt sets the "verified_at" field.
func (ituo *ItemTagUpdateOne) SetVerifiedAt(t time.Time) *ItemTagUpdateOne {
	ituo.mutation.SetVerifiedAt(t)
	return ituo
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (ituo *ItemTagUpdateOne) SetNillableVerifiedAt(t *time.Time) *ItemTagUpdateOne {
	if t != nil {
		ituo.SetVerifiedAt(*t)
	}
	return ituo
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (ituo *ItemTagUpdateOne) ClearVerifiedAt() *ItemTagUpdateOne {
	ituo.mutation.ClearVerifiedAt()
	return ituo
}

// SetLastScannedAt sets the "last_scanned_at" field.
func (ituo *ItemTagUpdateOne) SetLastScannedAt(t time.Time) *ItemTagUpdateOne {
	ituo.mutation.SetLastScannedAt(t)
	return ituo
}

// SetNillableLastScannedAt sets the "last_scanned_at" field if the given value is not nil.
func (ituo *ItemTagUpdateOne) SetNillableLastScannedAt(t *time.Time) *ItemTagUpdateOne {
	if t != nil {
		ituo.SetLastScannedAt(*t)
	}
	return ituo
}

// ClearLastScannedAt clears the value of the "last_scanned_at" field.
func (ituo *ItemTagUpdateOne) ClearLastScannedAt() *ItemTagUpdateOne {
	ituo.mutation.ClearLastScannedAt()
	return ituo
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (ituo *ItemTagUpdateOne) SetItemID(id uuid.UUID) *ItemTagUpdateOne {
	ituo.mutation.SetItemID(id)
	return ituo
}

// SetItem sets the "item" edge to the Item entity.
func (ituo *ItemTagUpdateOne) SetItem(i *Item) *ItemTagUpdateOne {
	return ituo.SetItemID(i.ID)
}

// Mutation returns the ItemTagMutation object of the builder.
func (ituo *ItemTagUpdateOne) Mutation() *ItemTagMutation {
	return ituo.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (ituo *ItemTagUpdateOne) ClearItem() *ItemTagUpdateOne {
	ituo.mutation.ClearItem()
	return ituo
}

// Where appends a list predicates to the ItemTagUpdate builder.
func (ituo *ItemTagUpdateOne) Where(ps ...predicate.ItemTag) *ItemTagUpdateOne {
	ituo.mutation.Where(ps...)
	return ituo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ituo *ItemTagUpdateOne) Select(field string, fields ...string) *ItemTagUpdateOne {
	ituo.fields = append([]string{field}, fields...)
	return ituo
}

// Save executes the query and returns the updated ItemTag entity.
func (ituo *ItemTagUpdateOne) Save(ctx context.Context) (*ItemTag, error) {
	ituo.defaults()
	return withHooks(ctx, ituo.sqlSave, ituo.mutation, ituo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ituo *ItemTagUpdateOne) SaveX(ctx context.Context) *ItemTag {
	node, err := ituo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ituo *ItemTagUpdateOne) Exec(ctx context.Context) error {
	_, err := ituo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ituo *ItemTagUpdateOne) ExecX(ctx context.Context) {
	if err := ituo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ituo *ItemTagUpdateOne) defaults() {
	if _, ok := ituo.mutation.UpdatedAt(); !ok {
		v := itemtag.UpdateDefaultUpdatedAt()
		ituo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ituo *ItemTagUpdateOne) check() error {
	if _, ok := ituo.mutation.ItemID(); ituo.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ItemTag.item"`)
	}
	return nil
}

func (ituo *ItemTagUpdateOne) sqlSave(ctx context.Context) (_node *ItemTag, err error) {
	if err := ituo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemtag.Table, itemtag.Columns, sqlgraph.NewFieldSpec(itemtag.FieldID, field.TypeUUID))
	id, ok := ituo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ituo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemtag.FieldID)
		for _, f := range fields {
			if !itemtag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ituo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ituo.mutation.UpdatedAt(); ok {
		_spec.SetField(itemtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ituo.mutation.RevokedAt(); ok {
		_spec.SetField(itemtag.FieldRevokedAt, field.TypeTime, value)
	}
	if ituo.mutation.RevokedAtCleared() {
		_spec.ClearField(itemtag.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := ituo.mutation.VerifiedAt(); ok {
		_spec.SetField(itemtag.FieldVerifiedAt, field.TypeTime, value)
	}
	if ituo.mutation.VerifiedAtCleared() {
		_spec.ClearField(itemtag.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := ituo.mutation.LastScannedAt(); ok {
		_spec.SetField(itemtag.FieldLastScannedAt, field.TypeTime, value)
	}
	if ituo.mutation.LastScannedAtCleared() {
		_spec.ClearField(itemtag.FieldLastScannedAt, field.TypeTime)
	}
	if ituo.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtag.ItemTable,
			Columns: []string{itemtag.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ituo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemtag.ItemTable,
			Columns: []string{itemtag.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ItemTag{config: ituo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ituo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ituo.mutation.done = true
	return _node, nil
}
