// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemevent"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemEventDelete is the builder for deleting a ItemEvent entity.
type ItemEventDelete struct {
	config
	hooks    []Hook
	mutation *ItemEventMutation
}

// Where appends a list predicates to the ItemEventDelete builder.
func (ied *ItemEventDelete) Where(ps ...predicate.ItemEvent) *ItemEventDelete {
	ied.mutation.Where(ps...)
	return ied
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ied *ItemEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ied.sqlExec, ied.mutation, ied.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ied *ItemEventDelete) ExecX(ctx context.Context) int {
	n, err := ied.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ied *ItemEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(itemevent.Table, sqlgraph.NewFieldSpec(itemevent.FieldID, field.TypeUUID))
	if ps := ied.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ied.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ied.mutation.done = true
	return affected, err
}

// ItemEventDeleteOne is the builder for deleting a single ItemEvent entity.
type ItemEventDeleteOne struct {
	ied *ItemEventDelete
}

// Where appends a list predicates to the ItemEventDelete builder.
func (iedo *ItemEventDeleteOne) Where(ps ...predicate.ItemEvent) *ItemEventDeleteOne {
	iedo.ied.mutation.Where(ps...)
	return iedo
}

// Exec executes the deletion query.
func (iedo *ItemEventDeleteOne) Exec(ctx context.Context) error {
	n, err := iedo.ied.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iedo *ItemEventDeleteOne) ExecX(ctx context.Context) {
	if err := iedo.Exec(ctx); err != nil {
		panic(err)
	}
}
