// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemtag"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemTagQuery is the builder for querying ItemTag entities.
type ItemTagQuery struct {
	config
	ctx        *QueryContext
	order      []itemtag.OrderOption
	inters     []Interceptor
	predicates []predicate.ItemTag
	withItem   *ItemQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ItemTagQuery builder.
func (itq *ItemTagQuery) Where(ps ...predicate.ItemTag) *ItemTagQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit the number of records to be returned by this query.
func (itq *ItemTagQuery) Limit(limit int) *ItemTagQuery {
	itq.ctx.Limit = &limit
	return itq
}

// Offset to start from.
func (itq *ItemTagQuery) Offset(offset int) *ItemTagQuery {
	itq.ctx.Offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *ItemTagQuery) Unique(unique bool) *ItemTagQuery {
	itq.ctx.Unique = &unique
	return itq
}

// Order specifies how the records should be ordered.
func (itq *ItemTagQuery) Order(o ...itemtag.OrderOption) *ItemTagQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// QueryItem chains the current query on the "item" edge.
func (itq *ItemTagQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: itq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(itemtag.Table, itemtag.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, itemtag.ItemTable, itemtag.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ItemTag entity from the query.
// Returns a *NotFoundError when no ItemTag was found.
func (itq *ItemTagQuery) First(ctx context.Context) (*ItemTag, error) {
	nodes, err := itq.Limit(1).All(setContextOp(ctx, itq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{itemtag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *ItemTagQuery) FirstX(ctx context.Context) *ItemTag {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ItemTag ID from the query.
// Returns a *NotFoundError when no ItemTag ID was found.
func (itq *ItemTagQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = itq.Limit(1).IDs(setContextOp(ctx, itq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{itemtag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *ItemTagQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ItemTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ItemTag entity is found.
// Returns a *NotFoundError when no ItemTag entities are found.
func (itq *ItemTagQuery) Only(ctx context.Context) (*ItemTag, error) {
	nodes, err := itq.Limit(2).All(setContextOp(ctx, itq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{itemtag.Label}
	default:
		return nil, &NotSingularError{itemtag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *ItemTagQuery) OnlyX(ctx context.Context) *ItemTag {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ItemTag ID in the query.
// Returns a *NotSingularError when more than one ItemTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *ItemTagQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = itq.Limit(2).IDs(setContextOp(ctx, itq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{itemtag.Label}
	default:
		err = &NotSingularError{itemtag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *ItemTagQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ItemTags.
func (itq *ItemTagQuery) All(ctx context.Context) ([]*ItemTag, error) {
	ctx = setContextOp(ctx, itq.ctx, "All")
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ItemTag, *ItemTagQuery]()
	return withInterceptors[[]*ItemTag](ctx, itq, qr, itq.inters)
}

// AllX is like All, but panics if an error occurs.
func (itq *ItemTagQuery) AllX(ctx context.Context) []*ItemTag {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ItemTag IDs.
func (itq *ItemTagQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if itq.ctx.Unique == nil && itq.path != nil {
		itq.Unique(true)
	}
	ctx = setContextOp(ctx, itq.ctx, "IDs")
	if err = itq.Select(itemtag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *ItemTagQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *ItemTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, itq.ctx, "Count")
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, itq, querierCount[*ItemTagQuery](), itq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (itq *ItemTagQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *ItemTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, itq.ctx, "Exist")
	switch _, err := itq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *ItemTagQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ItemTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *ItemTagQuery) Clone() *ItemTagQuery {
	if itq == nil {
		return nil
	}
	return &ItemTagQuery{
		config:     itq.config,
		ctx:        itq.ctx.Clone(),
		order:      append([]itemtag.OrderOption{}, itq.order...),
		inters:     append([]Interceptor{}, itq.inters...),
		predicates: append([]predicate.ItemTag{}, itq.predicates...),
		withItem:   itq.withItem.Clone(),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *ItemTagQuery) WithItem(opts ...func(*ItemQuery)) *ItemTagQuery {
	query := (&ItemClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	itq.withItem = query
	return itq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ItemTag.Query().
//		GroupBy(itemtag.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (itq *ItemTagQuery) GroupBy(field string, fields ...string) *ItemTagGroupBy {
	itq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ItemTagGroupBy{build: itq}
	grbuild.flds = &itq.ctx.Fields
	grbuild.label = itemtag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ItemTag.Query().
//		Select(itemtag.FieldCreatedAt).
//		Scan(ctx, &v)
func (itq *ItemTagQuery) Select(fields ...string) *ItemTagSelect {
	itq.ctx.Fields = append(itq.ctx.Fields, fields...)
	sbuild := &ItemTagSelect{ItemTagQuery: itq}
	sbuild.label = itemtag.Label
	sbuild.flds, sbuild.scan = &itq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ItemTagSelect configured with the given aggregations.
func (itq *ItemTagQuery) Aggregate(fns ...AggregateFunc) *ItemTagSelect {
	return itq.Select().Aggregate(fns...)
}

func (itq *ItemTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range itq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, itq); err != nil {
				return err
			}
		}
	}
	for _, f := range itq.ctx.Fields {
		if !itemtag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *ItemTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ItemTag, error) {
	var (
		nodes       = []*ItemTag{}
		withFKs     = itq.withFKs
		_spec       = itq.querySpec()
		loadedTypes = [1]bool{
			itq.withItem != nil,
		}
	)
	if itq.withItem != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, itemtag.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ItemTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ItemTag{config: itq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := itq.withItem; query != nil {
		if err := itq.loadItem(ctx, query, nodes, nil,
			func(n *ItemTag, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (itq *ItemTagQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*ItemTag, init func(*ItemTag), assign func(*ItemTag, *Item)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ItemTag)
	for i := range nodes {
		if nodes[i].item_tags == nil {
			continue
		}
		fk := *nodes[i].item_tags
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_tags" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (itq *ItemTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	_spec.Node.Columns = itq.ctx.Fields
	if len(itq.ctx.Fields) > 0 {
		_spec.Unique = itq.ctx.Unique != nil && *itq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *ItemTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(itemtag.Table, itemtag.Columns, sqlgraph.NewFieldSpec(itemtag.FieldID, field.TypeUUID))
	_spec.From = itq.sql
	if unique := itq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if itq.path != nil {
		_spec.Unique = true
	}
	if fields := itq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemtag.FieldID)
		for i := range fields {
			if fields[i] != itemtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *ItemTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(itemtag.Table)
	columns := itq.ctx.Fields
	if len(columns) == 0 {
		columns = itemtag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.ctx.Unique != nil && *itq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ItemTagGroupBy is the group-by builder for ItemTag entities.
type ItemTagGroupBy struct {
	selector
	build *ItemTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *ItemTagGroupBy) Aggregate(fns ...AggregateFunc) *ItemTagGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the selector query and scans the result into the given value.
func (itgb *ItemTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, itgb.build.ctx, "GroupBy")
	if err := itgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ItemTagQuery, *ItemTagGroupBy](ctx, itgb.build, itgb, itgb.build.inters, v)
}

func (itgb *ItemTagGroupBy) sqlScan(ctx context.Context, root *ItemTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*itgb.flds)+len(itgb.fns))
		for _, f := range *itgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*itgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ItemTagSelect is the builder for selecting fields of ItemTag entities.
type ItemTagSelect struct {
	*ItemTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (its *ItemTagSelect) Aggregate(fns ...AggregateFunc) *ItemTagSelect {
	its.fns = append(its.fns, fns...)
	return its
}

// Scan applies the selector query and scans the result into the given value.
func (its *ItemTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, its.ctx, "Select")
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ItemTagQuery, *ItemTagSelect](ctx, its.ItemTagQuery, its, its.inters, v)
}

func (its *ItemTagSelect) sqlScan(ctx context.Context, root *ItemTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(its.fns))
	for _, fn := range its.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*its.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
