// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemevent"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemEventQuery is the builder for querying ItemEvent entities.
type ItemEventQuery struct {
	config
	ctx        *QueryContext
	order      []itemevent.OrderOption
	inters     []Interceptor
	predicates []predicate.ItemEvent
	withItem   *ItemQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ItemEventQuery builder.
func (ieq *ItemEventQuery) Where(ps ...predicate.ItemEvent) *ItemEventQuery {
	ieq.predicates = append(ieq.predicates, ps...)
	return ieq
}

// Limit the number of records to be returned by this query.
func (ieq *ItemEventQuery) Limit(limit int) *ItemEventQuery {
	ieq.ctx.Limit = &limit
	return ieq
}

// Offset to start from.
func (ieq *ItemEventQuery) Offset(offset int) *ItemEventQuery {
	ieq.ctx.Offset = &offset
	return ieq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ieq *ItemEventQuery) Unique(unique bool) *ItemEventQuery {
	ieq.ctx.Unique = &unique
	return ieq
}

// Order specifies how the records should be ordered.
func (ieq *ItemEventQuery) Order(o ...itemevent.OrderOption) *ItemEventQuery {
	ieq.order = append(ieq.order, o...)
	return ieq
}

// QueryItem chains the current query on the "item" edge.
func (ieq *ItemEventQuery) QueryItem() *ItemQuery {
	query := (&ItemClient{config: ieq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ieq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ieq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(itemevent.Table, itemevent.FieldID, selector),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, itemevent.ItemTable, itemevent.ItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(ieq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ItemEvent entity from the query.
// Returns a *NotFoundError when no ItemEvent was found.
func (ieq *ItemEventQuery) First(ctx context.Context) (*ItemEvent, error) {
	nodes, err := ieq.Limit(1).All(setContextOp(ctx, ieq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{itemevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ieq *ItemEventQuery) FirstX(ctx context.Context) *ItemEvent {
	node, err := ieq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ItemEvent ID from the query.
// Returns a *NotFoundError when no ItemEvent ID was found.
func (ieq *ItemEventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ieq.Limit(1).IDs(setContextOp(ctx, ieq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{itemevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ieq *ItemEventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ieq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ItemEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ItemEvent entity is found.
// Returns a *NotFoundError when no ItemEvent entities are found.
func (ieq *ItemEventQuery) Only(ctx context.Context) (*ItemEvent, error) {
	nodes, err := ieq.Limit(2).All(setContextOp(ctx, ieq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{itemevent.Label}
	default:
		return nil, &NotSingularError{itemevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ieq *ItemEventQuery) OnlyX(ctx context.Context) *ItemEvent {
	node, err := ieq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ItemEvent ID in the query.
// Returns a *NotSingularError when more than one ItemEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (ieq *ItemEventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ieq.Limit(2).IDs(setContextOp(ctx, ieq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{itemevent.Label}
	default:
		err = &NotSingularError{itemevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ieq *ItemEventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ieq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ItemEvents.
func (ieq *ItemEventQuery) All(ctx context.Context) ([]*ItemEvent, error) {
	ctx = setContextOp(ctx, ieq.ctx, "All")
	if err := ieq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ItemEvent, *ItemEventQuery]()
	return withInterceptors[[]*ItemEvent](ctx, ieq, qr, ieq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ieq *ItemEventQuery) AllX(ctx context.Context) []*ItemEvent {
	nodes, err := ieq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ItemEvent IDs.
func (ieq *ItemEventQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ieq.ctx.Unique == nil && ieq.path != nil {
		ieq.Unique(true)
	}
	ctx = setContextOp(ctx, ieq.ctx, "IDs")
	if err = ieq.Select(itemevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ieq *ItemEventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ieq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ieq *ItemEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ieq.ctx, "Count")
	if err := ieq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ieq, querierCount[*ItemEventQuery](), ieq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ieq *ItemEventQuery) CountX(ctx context.Context) int {
	count, err := ieq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ieq *ItemEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ieq.ctx, "Exist")
	switch _, err := ieq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ieq *ItemEventQuery) ExistX(ctx context.Context) bool {
	exist, err := ieq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ItemEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ieq *ItemEventQuery) Clone() *ItemEventQuery {
	if ieq == nil {
		return nil
	}
	return &ItemEventQuery{
		config:     ieq.config,
		ctx:        ieq.ctx.Clone(),
		order:      append([]itemevent.OrderOption{}, ieq.order...),
		inters:     append([]Interceptor{}, ieq.inters...),
		predicates: append([]predicate.ItemEvent{}, ieq.predicates...),
		withItem:   ieq.withItem.Clone(),
		// clone intermediate query.
		sql:  ieq.sql.Clone(),
		path: ieq.path,
	}
}

// WithItem tells the query-builder to eager-load the nodes that are connected to
// the "item" edge. The optional arguments are used to configure the query builder of the edge.
func (ieq *ItemEventQuery) WithItem(opts ...func(*ItemQuery)) *ItemEventQuery {
	query := (&ItemClient{config: ieq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ieq.withItem = query
	return ieq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ItemEvent.Query().
//		GroupBy(itemevent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ieq *ItemEventQuery) GroupBy(field string, fields ...string) *ItemEventGroupBy {
	ieq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ItemEventGroupBy{build: ieq}
	grbuild.flds = &ieq.ctx.Fields
	grbuild.label = itemevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ItemEvent.Query().
//		Select(itemevent.FieldCreatedAt).
//		Scan(ctx, &v)
func (ieq *ItemEventQuery) Select(fields ...string) *ItemEventSelect {
	ieq.ctx.Fields = append(ieq.ctx.Fields, fields...)
	sbuild := &ItemEventSelect{ItemEventQuery: ieq}
	sbuild.label = itemevent.Label
	sbuild.flds, sbuild.scan = &ieq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ItemEventSelect configured with the given aggregations.
func (ieq *ItemEventQuery) Aggregate(fns ...AggregateFunc) *ItemEventSelect {
	return ieq.Select().Aggregate(fns...)
}

func (ieq *ItemEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ieq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ieq); err != nil {
				return err
			}
		}
	}
	for _, f := range ieq.ctx.Fields {
		if !itemevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ieq.path != nil {
		prev, err := ieq.path(ctx)
		if err != nil {
			return err
		}
		ieq.sql = prev
	}
	return nil
}

func (ieq *ItemEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ItemEvent, error) {
	var (
		nodes       = []*ItemEvent{}
		withFKs     = ieq.withFKs
		_spec       = ieq.querySpec()
		loadedTypes = [1]bool{
			ieq.withItem != nil,
		}
	)
	if ieq.withItem != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, itemevent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ItemEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ItemEvent{config: ieq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ieq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ieq.withItem; query != nil {
		if err := ieq.loadItem(ctx, query, nodes, nil,
			func(n *ItemEvent, e *Item) { n.Edges.Item = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ieq *ItemEventQuery) loadItem(ctx context.Context, query *ItemQuery, nodes []*ItemEvent, init func(*ItemEvent), assign func(*ItemEvent, *Item)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ItemEvent)
	for i := range nodes {
		if nodes[i].item_events == nil {
			continue
		}
		fk := *nodes[i].item_events
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(item.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "item_events" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ieq *ItemEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ieq.querySpec()
	_spec.Node.Columns = ieq.ctx.Fields
	if len(ieq.ctx.Fields) > 0 {
		_spec.Unique = ieq.ctx.Unique != nil && *ieq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ieq.driver, _spec)
}

func (ieq *ItemEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(itemevent.Table, itemevent.Columns, sqlgraph.NewFieldSpec(itemevent.FieldID, field.TypeUUID))
	_spec.From = ieq.sql
	if unique := ieq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ieq.path != nil {
		_spec.Unique = true
	}
	if fields := ieq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemevent.FieldID)
		for i := range fields {
			if fields[i] != itemevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ieq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ieq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ieq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ieq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ieq *ItemEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ieq.driver.Dialect())
	t1 := builder.Table(itemevent.Table)
	columns := ieq.ctx.Fields
	if len(columns) == 0 {
		columns = itemevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ieq.sql != nil {
		selector = ieq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ieq.ctx.Unique != nil && *ieq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ieq.predicates {
		p(selector)
	}
	for _, p := range ieq.order {
		p(selector)
	}
	if offset := ieq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ieq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ItemEventGroupBy is the group-by builder for ItemEvent entities.
type ItemEventGroupBy struct {
	selector
	build *ItemEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iegb *ItemEventGroupBy) Aggregate(fns ...AggregateFunc) *ItemEventGroupBy {
	iegb.fns = append(iegb.fns, fns...)
	return iegb
}

// Scan applies the selector query and scans the result into the given value.
func (iegb *ItemEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iegb.build.ctx, "GroupBy")
	if err := iegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ItemEventQuery, *ItemEventGroupBy](ctx, iegb.build, iegb, iegb.build.inters, v)
}

func (iegb *ItemEventGroupBy) sqlScan(ctx context.Context, root *ItemEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(iegb.fns))
	for _, fn := range iegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*iegb.flds)+len(iegb.fns))
		for _, f := range *iegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*iegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ItemEventSelect is the builder for selecting fields of ItemEvent entities.
type ItemEventSelect struct {
	*ItemEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ies *ItemEventSelect) Aggregate(fns ...AggregateFunc) *ItemEventSelect {
	ies.fns = append(ies.fns, fns...)
	return ies
}

// Scan applies the selector query and scans the result into the given value.
func (ies *ItemEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ies.ctx, "Select")
	if err := ies.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ItemEventQuery, *ItemEventSelect](ctx, ies.ItemEventQuery, ies, ies.inters, v)
}

func (ies *ItemEventSelect) sqlScan(ctx context.Context, root *ItemEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ies.fns))
	for _, fn := range ies.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ies.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ies.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
