// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemevent"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ItemEventUpdate is the builder for updating ItemEvent entities.
type ItemEventUpdate struct {
	config
	hooks    []Hook
	mutation *ItemEventMutation
}

// Where appends a list predicates to the ItemEventUpdate builder.
func (ieu *ItemEventUpdate) Where(ps ...predicate.ItemEvent) *ItemEventUpdate {
	ieu.mutation.Where(ps...)
	return ieu
}

// SetUpdatedAt sets the "updated_at" field.
func (ieu *ItemEventUpdate) SetUpdatedAt(t time.Time) *ItemEventUpdate {
	ieu.mutation.SetUpdatedAt(t)
	return ieu
}

// SetKind sets the "kind" field.
func (ieu *ItemEventUpdate) SetKind(s string) *ItemEventUpdate {
	ieu.mutation.SetKind(s)
	return ieu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (ieu *ItemEventUpdate) SetNillableKind(s *string) *ItemEventUpdate {
	if s != nil {
		ieu.SetKind(*s)
	}
	return ieu
}

// SetSummary sets the "summary" field.
func (ieu *ItemEventUpdate) SetSummary(s string) *ItemEventUpdate {
	ieu.mutation.SetSummary(s)
	return ieu
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (ieu *ItemEventUpdate) SetNillableSummary(s *string) *ItemEventUpdate {
	if s != nil {
		ieu.SetSummary(*s)
	}
	return ieu
}

// SetNote sets the "note" field.
func (ieu *ItemEventUpdate) SetNote(s string) *ItemEventUpdate {
	ieu.mutation.SetNote(s)
	return ieu
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ieu *ItemEventUpdate) SetNillableNote(s *string) *ItemEventUpdate {
	if s != nil {
		ieu.SetNote(*s)
	}
	return ieu
}

// ClearNote clears the value of the "note" field.
func (ieu *ItemEventUpdate) ClearNote() *ItemEventUpdate {
	ieu.mutation.ClearNote()
	return ieu
}

// SetActorName sets the "actor_name" field.
func (ieu *ItemEventUpdate) SetActorName(s string) *ItemEventUpdate {
	ieu.mutation.SetActorName(s)
	return ieu
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (ieu *ItemEventUpdate) SetNillableActorName(s *string) *ItemEventUpdate {
	if s != nil {
		ieu.SetActorName(*s)
	}
	return ieu
}

// ClearActorName clears the value of the "actor_name" field.
func (ieu *ItemEventUpdate) ClearActorName() *ItemEventUpdate {
	ieu.mutation.ClearActorName()
	return ieu
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (ieu *ItemEventUpdate) SetItemID(id uuid.UUID) *ItemEventUpdate {
	ieu.mutation.SetItemID(id)
	return ieu
}

// SetItem sets the "item" edge to the Item entity.
func (ieu *ItemEventUpdate) SetItem(i *Item) *ItemEventUpdate {
	return ieu.SetItemID(i.ID)
}

// Mutation returns the ItemEventMutation object of the builder.
func (ieu *ItemEventUpdate) Mutation() *ItemEventMutation {
	return ieu.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (ieu *ItemEventUpdate) ClearItem() *ItemEventUpdate {
	ieu.mutation.ClearItem()
	return ieu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ieu *ItemEventUpdate) Save(ctx context.Context) (int, error) {
	ieu.defaults()
	return withHooks(ctx, ieu.sqlSave, ieu.mutation, ieu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ieu *ItemEventUpdate) SaveX(ctx context.Context) int {
	affected, err := ieu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ieu *ItemEventUpdate) Exec(ctx context.Context) error {
	_, err := ieu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ieu *ItemEventUpdate) ExecX(ctx context.Context) {
	if err := ieu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ieu *ItemEventUpdate) defaults() {
	if _, ok := ieu.mutation.UpdatedAt(); !ok {
		v := itemevent.UpdateDefaultUpdatedAt()
		ieu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ieu *ItemEventUpdate) check() error {
	if v, ok := ieu.mutation.Kind(); ok {
		if err := itemevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.kind": %w`, err)}
		}
	}
	if v, ok := ieu.mutation.Summary(); ok {
		if err := itemevent.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.summary": %w`, err)}
		}
	}
	if v, ok := ieu.mutation.Note(); ok {
		if err := itemevent.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.note": %w`, err)}
		}
	}
	if v, ok := ieu.mutation.ActorName(); ok {
		if err := itemevent.ActorNameValidator(v); err != nil {
			return &ValidationError{Name: "actor_name", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.actor_name": %w`, err)}
		}
	}
	if _, ok := ieu.mutation.ItemID(); ieu.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ItemEvent.item"`)
	}
	return nil
}

func (ieu *ItemEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ieu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemevent.Table, itemevent.Columns, sqlgraph.NewFieldSpec(itemevent.FieldID, field.TypeUUID))
	if ps := ieu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ieu.mutation.UpdatedAt(); ok {
		_spec.SetField(itemevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ieu.mutation.Kind(); ok {
		_spec.SetField(itemevent.FieldKind, field.TypeString, value)
	}
	if value, ok := ieu.mutation.Summary(); ok {
		_spec.SetField(itemevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := ieu.mutation.Note(); ok {
		_spec.SetField(itemevent.FieldNote, field.TypeString, value)
	}
	if ieu.mutation.NoteCleared() {
		_spec.ClearField(itemevent.FieldNote, field.TypeString)
	}
	if value, ok := ieu.mutation.ActorName(); ok {
		_spec.SetField(itemevent.FieldActorName, field.TypeString, value)
	}
	if ieu.mutation.ActorNameCleared() {
		_spec.ClearField(itemevent.FieldActorName, field.TypeString)
	}
	if ieu.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemevent.ItemTable,
			Columns: []string{itemevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ieu.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemevent.ItemTable,
			Columns: []string{itemevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ieu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ieu.mutation.done = true
	return n, nil
}

// ItemEventUpdateOne is the builder for updating a single ItemEvent entity.
type ItemEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ieuo *ItemEventUpdateOne) SetUpdatedAt(t time.Time) *ItemEventUpdateOne {
	ieuo.mutation.SetUpdatedAt(t)
	return ieuo
}

// SetKind sets the "kind" field.
func (ieuo *ItemEventUpdateOne) SetKind(s string) *ItemEventUpdateOne {
	ieuo.mutation.SetKind(s)
	return ieuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (ieuo *ItemEventUpdateOne) SetNillableKind(s *string) *ItemEventUpdateOne {
	if s != nil {
		ieuo.SetKind(*s)
	}
	return ieuo
}

// SetSummary sets the "summary" field.
func (ieuo *ItemEventUpdateOne) SetSummary(s string) *ItemEventUpdateOne {
	ieuo.mutation.SetSummary(s)
	return ieuo
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (ieuo *ItemEventUpdateOne) SetNillableSummary(s *string) *ItemEventUpdateOne {
	if s != nil {
		ieuo.SetSummary(*s)
	}
	return ieuo
}

// SetNote sets the "note" field.
func (ieuo *ItemEventUpdateOne) SetNote(s string) *ItemEventUpdateOne {
	ieuo.mutation.SetNote(s)
	return ieuo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ieuo *ItemEventUpdateOne) SetNillableNote(s *string) *ItemEventUpdateOne {
	if s != nil {
		ieuo.SetNote(*s)
	}
	return ieuo
}

// ClearNote clears the value of the "note" field.
func (ieuo *ItemEventUpdateOne) ClearNote() *ItemEventUpdateOne {
	ieuo.mutation.ClearNote()
	return ieuo
}

// SetActorName sets the "actor_name" field.
func (ieuo *ItemEventUpdateOne) SetActorName(s string) *ItemEventUpdateOne {
	ieuo.mutation.SetActorName(s)
	return ieuo
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (ieuo *ItemEventUpdateOne) SetNillableActorName(s *string) *ItemEventUpdateOne {
	if s != nil {
		ieuo.SetActorName(*s)
	}
	return ieuo
}

// ClearActorName clears the value of the "actor_name" field.
func (ieuo *ItemEventUpdateOne) ClearActorName() *ItemEventUpdateOne {
	ieuo.mutation.ClearActorName()
	return ieuo
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (ieuo *ItemEventUpdateOne) SetItemID(id uuid.UUID) *ItemEventUpdateOne {
	ieuo.mutation.SetItemID(id)
	return ieuo
}

// SetItem sets the "item" edge to the Item entity.
func (ieuo *ItemEventUpdateOne) SetItem(i *Item) *ItemEventUpdateOne {
	return ieuo.SetItemID(i.ID)
}

// Mutation returns the ItemEventMutation object of the builder.
func (ieuo *ItemEventUpdateOne) Mutation() *ItemEventMutation {
	return ieuo.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (ieuo *ItemEventUpdateOne) ClearItem() *ItemEventUpdateOne {
	ieuo.mutation.ClearItem()
	return ieuo
}

// Where appends a list predicates to the ItemEventUpdate builder.
func (ieuo *ItemEventUpdateOne) Where(ps ...predicate.ItemEvent) *ItemEventUpdateOne {
	ieuo.mutation.Where(ps...)
	return ieuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ieuo *ItemEventUpdateOne) Select(field string, fields ...string) *ItemEventUpdateOne {
	ieuo.fields = append([]string{field}, fields...)
	return ieuo
}

// Save executes the query and returns the updated ItemEvent entity.
func (ieuo *ItemEventUpdateOne) Save(ctx context.Context) (*ItemEvent, error) {
	ieuo.defaults()
	return withHooks(ctx, ieuo.sqlSave, ieuo.mutation, ieuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ieuo *ItemEventUpdateOne) SaveX(ctx context.Context) *ItemEvent {
	node, err := ieuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ieuo *ItemEventUpdateOne) Exec(ctx context.Context) error {
	_, err := ieuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ieuo *ItemEventUpdateOne) ExecX(ctx context.Context) {
	if err := ieuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ieuo *ItemEventUpdateOne) defaults() {
	if _, ok := ieuo.mutation.UpdatedAt(); !ok {
		v := itemevent.UpdateDefaultUpdatedAt()
		ieuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ieuo *ItemEventUpdateOne) check() error {
	if v, ok := ieuo.mutation.Kind(); ok {
		if err := itemevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.kind": %w`, err)}
		}
	}
	if v, ok := ieuo.mutation.Summary(); ok {
		if err := itemevent.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.summary": %w`, err)}
		}
	}
	if v, ok := ieuo.mutation.Note(); ok {
		if err := itemevent.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.note": %w`, err)}
		}
	}
	if v, ok := ieuo.mutation.ActorName(); ok {
		if err := itemevent.ActorNameValidator(v); err != nil {
			return &ValidationError{Name: "actor_name", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.actor_name": %w`, err)}
		}
	}
	if _, ok := ieuo.mutation.ItemID(); ieuo.mutation.ItemCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ItemEvent.item"`)
	}
	return nil
}

func (ieuo *ItemEventUpdateOne) sqlSave(ctx context.Context) (_node *ItemEvent, err error) {
	if err := ieuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemevent.Table, itemevent.Columns, sqlgraph.NewFieldSpec(itemevent.FieldID, field.TypeUUID))
	id, ok := ieuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ieuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemevent.FieldID)
		for _, f := range fields {
			if !itemevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ieuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ieuo.mutation.UpdatedAt(); ok {
		_spec.SetField(itemevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ieuo.mutation.Kind(); ok {
		_spec.SetField(itemevent.FieldKind, field.TypeString, value)
	}
	if value, ok := ieuo.mutation.Summary(); ok {
		_spec.SetField(itemevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := ieuo.mutation.Note(); ok {
		_spec.SetField(itemevent.FieldNote, field.TypeString, value)
	}
	if ieuo.mutation.NoteCleared() {
		_spec.ClearField(itemevent.FieldNote, field.TypeString)
	}
	if value, ok := ieuo.mutation.ActorName(); ok {
		_spec.SetField(itemevent.FieldActorName, field.TypeString, value)
	}
	if ieuo.mutation.ActorNameCleared() {
		_spec.ClearField(itemevent.FieldActorName, field.TypeString)
	}
	if ieuo.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemevent.ItemTable,
			Columns: []string{itemevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ieuo.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemevent.ItemTable,
			Columns: []string{itemevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ItemEvent{config: ieuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ieuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ieuo.mutation.done = true
	return _node, nil
}
