// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/item"
	"github.com/sdmad737/catalog/backend/internal/data/ent/itemevent"
)

// ItemEventCreate is the builder for creating a ItemEvent entity.
type ItemEventCreate struct {
	config
	mutation *ItemEventMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (iec *ItemEventCreate) SetCreatedAt(t time.Time) *ItemEventCreate {
	iec.mutation.SetCreatedAt(t)
	return iec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iec *ItemEventCreate) SetNillableCreatedAt(t *time.Time) *ItemEventCreate {
	if t != nil {
		iec.SetCreatedAt(*t)
	}
	return iec
}

// SetUpdatedAt sets the "updated_at" field.
func (iec *ItemEventCreate) SetUpdatedAt(t time.Time) *ItemEventCreate {
	iec.mutation.SetUpdatedAt(t)
	return iec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (iec *ItemEventCreate) SetNillableUpdatedAt(t *time.Time) *ItemEventCreate {
	if t != nil {
		iec.SetUpdatedAt(*t)
	}
	return iec
}

// SetKind sets the "kind" field.
func (iec *ItemEventCreate) SetKind(s string) *ItemEventCreate {
	iec.mutation.SetKind(s)
	return iec
}

// SetSummary sets the "summary" field.
func (iec *ItemEventCreate) SetSummary(s string) *ItemEventCreate {
	iec.mutation.SetSummary(s)
	return iec
}

// SetNote sets the "note" field.
func (iec *ItemEventCreate) SetNote(s string) *ItemEventCreate {
	iec.mutation.SetNote(s)
	return iec
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (iec *ItemEventCreate) SetNillableNote(s *string) *ItemEventCreate {
	if s != nil {
		iec.SetNote(*s)
	}
	return iec
}

// SetActorName sets the "actor_name" field.
func (iec *ItemEventCreate) SetActorName(s string) *ItemEventCreate {
	iec.mutation.SetActorName(s)
	return iec
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (iec *ItemEventCreate) SetNillableActorName(s *string) *ItemEventCreate {
	if s != nil {
		iec.SetActorName(*s)
	}
	return iec
}

// SetID sets the "id" field.
func (iec *ItemEventCreate) SetID(u uuid.UUID) *ItemEventCreate {
	iec.mutation.SetID(u)
	return iec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (iec *ItemEventCreate) SetNillableID(u *uuid.UUID) *ItemEventCreate {
	if u != nil {
		iec.SetID(*u)
	}
	return iec
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (iec *ItemEventCreate) SetItemID(id uuid.UUID) *ItemEventCreate {
	iec.mutation.SetItemID(id)
	return iec
}

// SetItem sets the "item" edge to the Item entity.
func (iec *ItemEventCreate) SetItem(i *Item) *ItemEventCreate {
	return iec.SetItemID(i.ID)
}

// Mutation returns the ItemEventMutation object of the builder.
func (iec *ItemEventCreate) Mutation() *ItemEventMutation {
	return iec.mutation
}

// Save creates the ItemEvent in the database.
func (iec *ItemEventCreate) Save(ctx context.Context) (*ItemEvent, error) {
	iec.defaults()
	return withHooks(ctx, iec.sqlSave, iec.mutation, iec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iec *ItemEventCreate) SaveX(ctx context.Context) *ItemEvent {
	v, err := iec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iec *ItemEventCreate) Exec(ctx context.Context) error {
	_, err := iec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iec *ItemEventCreate) ExecX(ctx context.Context) {
	if err := iec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iec *ItemEventCreate) defaults() {
	if _, ok := iec.mutation.CreatedAt(); !ok {
		v := itemevent.DefaultCreatedAt()
		iec.mutation.SetCreatedAt(v)
	}
	if _, ok := iec.mutation.UpdatedAt(); !ok {
		v := itemevent.DefaultUpdatedAt()
		iec.mutation.SetUpdatedAt(v)
	}
	if _, ok := iec.mutation.ID(); !ok {
		v := itemevent.DefaultID()
		iec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iec *ItemEventCreate) check() error {
	if _, ok := iec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemEvent.created_at"`)}
	}
	if _, ok := iec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemEvent.updated_at"`)}
	}
	if _, ok := iec.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ItemEvent.kind"`)}
	}
	if v, ok := iec.mutation.Kind(); ok {
		if err := itemevent.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.kind": %w`, err)}
		}
	}
	if _, ok := iec.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "ItemEvent.summary"`)}
	}
	if v, ok := iec.mutation.Summary(); ok {
		if err := itemevent.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.summary": %w`, err)}
		}
	}
	if v, ok := iec.mutation.Note(); ok {
		if err := itemevent.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.note": %w`, err)}
		}
	}
	if v, ok := iec.mutation.ActorName(); ok {
		if err := itemevent.ActorNameValidator(v); err != nil {
			return &ValidationError{Name: "actor_name", err: fmt.Errorf(`ent: validator failed for field "ItemEvent.actor_name": %w`, err)}
		}
	}
	if _, ok := iec.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ItemEvent.item"`)}
	}
	return nil
}

func (iec *ItemEventCreate) sqlSave(ctx context.Context) (*ItemEvent, error) {
	if err := iec.check(); err != nil {
		return nil, err
	}
	_node, _spec := iec.createSpec()
	if err := sqlgraph.CreateNode(ctx, iec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	iec.mutation.id = &_node.ID
	iec.mutation.done = true
	return _node, nil
}

func (iec *ItemEventCreate) createSpec() (*ItemEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemEvent{config: iec.config}
		_spec = sqlgraph.NewCreateSpec(itemevent.Table, sqlgraph.NewFieldSpec(itemevent.FieldID, field.TypeUUID))
	)
	if id, ok := iec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := iec.mutation.CreatedAt(); ok {
		_spec.SetField(itemevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := iec.mutation.UpdatedAt(); ok {
		_spec.SetField(itemevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := iec.mutation.Kind(); ok {
		_spec.SetField(itemevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := iec.mutation.Summary(); ok {
		_spec.SetField(itemevent.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := iec.mutation.Note(); ok {
		_spec.SetField(itemevent.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := iec.mutation.ActorName(); ok {
		_spec.SetField(itemevent.FieldActorName, field.TypeString, value)
		_node.ActorName = value
	}
	if nodes := iec.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemevent.ItemTable,
			Columns: []string{itemevent.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ItemEventCreateBulk is the builder for creating many ItemEvent entities in bulk.
type ItemEventCreateBulk struct {
	config
	err      error
	builders []*ItemEventCreate
}

// Save creates the ItemEvent entities in the database.
func (iecb *ItemEventCreateBulk) Save(ctx context.Context) ([]*ItemEvent, error) {
	if iecb.err != nil {
		return nil, iecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iecb.builders))
	nodes := make([]*ItemEvent, len(iecb.builders))
	mutators := make([]Mutator, len(iecb.builders))
	for i := range iecb.builders {
		func(i int, root context.Context) {
			builder := iecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iecb *ItemEventCreateBulk) SaveX(ctx context.Context) []*ItemEvent {
	v, err := iecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iecb *ItemEventCreateBulk) Exec(ctx context.Context) error {
	_, err := iecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iecb *ItemEventCreateBulk) ExecX(ctx context.Context) {
	if err := iecb.Exec(ctx); err != nil {
		panic(err)
	}
}
