// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/checkout"
	"github.com/sdmad737/catalog/backend/internal/data/ent/group"
	"github.com/sdmad737/catalog/backend/internal/data/ent/person"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// PersonUpdate is the builder for updating Person entities.
type PersonUpdate struct {
	config
	hooks    []Hook
	mutation *PersonMutation
}

// Where appends a list predicates to the PersonUpdate builder.
func (pu *PersonUpdate) Where(ps ...predicate.Person) *PersonUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PersonUpdate) SetUpdatedAt(t time.Time) *PersonUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetName sets the "name" field.
func (pu *PersonUpdate) SetName(s string) *PersonUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *PersonUpdate) SetNillableName(s *string) *PersonUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetEmail sets the "email" field.
func (pu *PersonUpdate) SetEmail(s string) *PersonUpdate {
	pu.mutation.SetEmail(s)
	return pu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (pu *PersonUpdate) SetNillableEmail(s *string) *PersonUpdate {
	if s != nil {
		pu.SetEmail(*s)
	}
	return pu
}

// ClearEmail clears the value of the "email" field.
func (pu *PersonUpdate) ClearEmail() *PersonUpdate {
	pu.mutation.ClearEmail()
	return pu
}

// SetIdentifier sets the "identifier" field.
func (pu *PersonUpdate) SetIdentifier(s string) *PersonUpdate {
	pu.mutation.SetIdentifier(s)
	return pu
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (pu *PersonUpdate) SetNillableIdentifier(s *string) *PersonUpdate {
	if s != nil {
		pu.SetIdentifier(*s)
	}
	return pu
}

// ClearIdentifier clears the value of the "identifier" field.
func (pu *PersonUpdate) ClearIdentifier() *PersonUpdate {
	pu.mutation.ClearIdentifier()
	return pu
}

// SetNotes sets the "notes" field.
func (pu *PersonUpdate) SetNotes(s string) *PersonUpdate {
	pu.mutation.SetNotes(s)
	return pu
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (pu *PersonUpdate) SetNillableNotes(s *string) *PersonUpdate {
	if s != nil {
		pu.SetNotes(*s)
	}
	return pu
}

// ClearNotes clears the value of the "notes" field.
func (pu *PersonUpdate) ClearNotes() *PersonUpdate {
	pu.mutation.ClearNotes()
	return pu
}

// SetActive sets the "active" field.
func (pu *PersonUpdate) SetActive(b bool) *PersonUpdate {
	pu.mutation.SetActive(b)
	return pu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (pu *PersonUpdate) SetNillableActive(b *bool) *PersonUpdate {
	if b != nil {
		pu.SetActive(*b)
	}
	return pu
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (pu *PersonUpdate) SetGroupID(id uuid.UUID) *PersonUpdate {
	pu.mutation.SetGroupID(id)
	return pu
}

// SetGroup sets the "group" edge to the Group entity.
func (pu *PersonUpdate) SetGroup(g *Group) *PersonUpdate {
	return pu.SetGroupID(g.ID)
}

// AddCheckoutIDs adds the "checkouts" edge to the Checkout entity by IDs.
func (pu *PersonUpdate) AddCheckoutIDs(ids ...uuid.UUID) *PersonUpdate {
	pu.mutation.AddCheckoutIDs(ids...)
	return pu
}

// AddCheckouts adds the "checkouts" edges to the Checkout entity.
func (pu *PersonUpdate) AddCheckouts(c ...*Checkout) *PersonUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pu.AddCheckoutIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (pu *PersonUpdate) Mutation() *PersonMutation {
	return pu.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (pu *PersonUpdate) ClearGroup() *PersonUpdate {
	pu.mutation.ClearGroup()
	return pu
}

// ClearCheckouts clears all "checkouts" edges to the Checkout entity.
func (pu *PersonUpdate) ClearCheckouts() *PersonUpdate {
	pu.mutation.ClearCheckouts()
	return pu
}

// RemoveCheckoutIDs removes the "checkouts" edge to Checkout entities by IDs.
func (pu *PersonUpdate) RemoveCheckoutIDs(ids ...uuid.UUID) *PersonUpdate {
	pu.mutation.RemoveCheckoutIDs(ids...)
	return pu
}

// RemoveCheckouts removes "checkouts" edges to Checkout entities.
func (pu *PersonUpdate) RemoveCheckouts(c ...*Checkout) *PersonUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pu.RemoveCheckoutIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PersonUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PersonUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PersonUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PersonUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PersonUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := person.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PersonUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := person.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Person.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Email(); ok {
		if err := person.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Person.email": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Identifier(); ok {
		if err := person.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Person.identifier": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Notes(); ok {
		if err := person.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Person.notes": %w`, err)}
		}
	}
	if _, ok := pu.mutation.GroupID(); pu.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Person.group"`)
	}
	return nil
}

func (pu *PersonUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Email(); ok {
		_spec.SetField(person.FieldEmail, field.TypeString, value)
	}
	if pu.mutation.EmailCleared() {
		_spec.ClearField(person.FieldEmail, field.TypeString)
	}
	if value, ok := pu.mutation.Identifier(); ok {
		_spec.SetField(person.FieldIdentifier, field.TypeString, value)
	}
	if pu.mutation.IdentifierCleared() {
		_spec.ClearField(person.FieldIdentifier, field.TypeString)
	}
	if value, ok := pu.mutation.Notes(); ok {
		_spec.SetField(person.FieldNotes, field.TypeString, value)
	}
	if pu.mutation.NotesCleared() {
		_spec.ClearField(person.FieldNotes, field.TypeString)
	}
	if value, ok := pu.mutation.Active(); ok {
		_spec.SetField(person.FieldActive, field.TypeBool, value)
	}
	if pu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.GroupTable,
			Columns: []string{person.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.GroupTable,
			Columns: []string{person.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.CheckoutsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedCheckoutsIDs(); len(nodes) > 0 && !pu.mutation.CheckoutsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.CheckoutsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PersonUpdateOne is the builder for updating a single Person entity.
type PersonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PersonUpdateOne) SetUpdatedAt(t time.Time) *PersonUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetName sets the "name" field.
func (puo *PersonUpdateOne) SetName(s string) *PersonUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *PersonUpdateOne) SetNillableName(s *string) *PersonUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetEmail sets the "email" field.
func (puo *PersonUpdateOne) SetEmail(s string) *PersonUpdateOne {
	puo.mutation.SetEmail(s)
	return puo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (puo *PersonUpdateOne) SetNillableEmail(s *string) *PersonUpdateOne {
	if s != nil {
		puo.SetEmail(*s)
	}
	return puo
}

// ClearEmail clears the value of the "email" field.
func (puo *PersonUpdateOne) ClearEmail() *PersonUpdateOne {
	puo.mutation.ClearEmail()
	return puo
}

// SetIdentifier sets the "identifier" field.
func (puo *PersonUpdateOne) SetIdentifier(s string) *PersonUpdateOne {
	puo.mutation.SetIdentifier(s)
	return puo
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (puo *PersonUpdateOne) SetNillableIdentifier(s *string) *PersonUpdateOne {
	if s != nil {
		puo.SetIdentifier(*s)
	}
	return puo
}

// ClearIdentifier clears the value of the "identifier" field.
func (puo *PersonUpdateOne) ClearIdentifier() *PersonUpdateOne {
	puo.mutation.ClearIdentifier()
	return puo
}

// SetNotes sets the "notes" field.
func (puo *PersonUpdateOne) SetNotes(s string) *PersonUpdateOne {
	puo.mutation.SetNotes(s)
	return puo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (puo *PersonUpdateOne) SetNillableNotes(s *string) *PersonUpdateOne {
	if s != nil {
		puo.SetNotes(*s)
	}
	return puo
}

// ClearNotes clears the value of the "notes" field.
func (puo *PersonUpdateOne) ClearNotes() *PersonUpdateOne {
	puo.mutation.ClearNotes()
	return puo
}

// SetActive sets the "active" field.
func (puo *PersonUpdateOne) SetActive(b bool) *PersonUpdateOne {
	puo.mutation.SetActive(b)
	return puo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (puo *PersonUpdateOne) SetNillableActive(b *bool) *PersonUpdateOne {
	if b != nil {
		puo.SetActive(*b)
	}
	return puo
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (puo *PersonUpdateOne) SetGroupID(id uuid.UUID) *PersonUpdateOne {
	puo.mutation.SetGroupID(id)
	return puo
}

// SetGroup sets the "group" edge to the Group entity.
func (puo *PersonUpdateOne) SetGroup(g *Group) *PersonUpdateOne {
	return puo.SetGroupID(g.ID)
}

// AddCheckoutIDs adds the "checkouts" edge to the Checkout entity by IDs.
func (puo *PersonUpdateOne) AddCheckoutIDs(ids ...uuid.UUID) *PersonUpdateOne {
	puo.mutation.AddCheckoutIDs(ids...)
	return puo
}

// AddCheckouts adds the "checkouts" edges to the Checkout entity.
func (puo *PersonUpdateOne) AddCheckouts(c ...*Checkout) *PersonUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return puo.AddCheckoutIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (puo *PersonUpdateOne) Mutation() *PersonMutation {
	return puo.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (puo *PersonUpdateOne) ClearGroup() *PersonUpdateOne {
	puo.mutation.ClearGroup()
	return puo
}

// ClearCheckouts clears all "checkouts" edges to the Checkout entity.
func (puo *PersonUpdateOne) ClearCheckouts() *PersonUpdateOne {
	puo.mutation.ClearCheckouts()
	return puo
}

// RemoveCheckoutIDs removes the "checkouts" edge to Checkout entities by IDs.
func (puo *PersonUpdateOne) RemoveCheckoutIDs(ids ...uuid.UUID) *PersonUpdateOne {
	puo.mutation.RemoveCheckoutIDs(ids...)
	return puo
}

// RemoveCheckouts removes "checkouts" edges to Checkout entities.
func (puo *PersonUpdateOne) RemoveCheckouts(c ...*Checkout) *PersonUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return puo.RemoveCheckoutIDs(ids...)
}

// Where appends a list predicates to the PersonUpdate builder.
func (puo *PersonUpdateOne) Where(ps ...predicate.Person) *PersonUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PersonUpdateOne) Select(field string, fields ...string) *PersonUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Person entity.
func (puo *PersonUpdateOne) Save(ctx context.Context) (*Person, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PersonUpdateOne) SaveX(ctx context.Context) *Person {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PersonUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PersonUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PersonUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := person.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PersonUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := person.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Person.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Email(); ok {
		if err := person.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Person.email": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Identifier(); ok {
		if err := person.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Person.identifier": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Notes(); ok {
		if err := person.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "Person.notes": %w`, err)}
		}
	}
	if _, ok := puo.mutation.GroupID(); puo.mutation.GroupCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Person.group"`)
	}
	return nil
}

func (puo *PersonUpdateOne) sqlSave(ctx context.Context) (_node *Person, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(person.Table, person.Columns, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Person.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, person.FieldID)
		for _, f := range fields {
			if !person.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != person.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(person.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Email(); ok {
		_spec.SetField(person.FieldEmail, field.TypeString, value)
	}
	if puo.mutation.EmailCleared() {
		_spec.ClearField(person.FieldEmail, field.TypeString)
	}
	if value, ok := puo.mutation.Identifier(); ok {
		_spec.SetField(person.FieldIdentifier, field.TypeString, value)
	}
	if puo.mutation.IdentifierCleared() {
		_spec.ClearField(person.FieldIdentifier, field.TypeString)
	}
	if value, ok := puo.mutation.Notes(); ok {
		_spec.SetField(person.FieldNotes, field.TypeString, value)
	}
	if puo.mutation.NotesCleared() {
		_spec.ClearField(person.FieldNotes, field.TypeString)
	}
	if value, ok := puo.mutation.Active(); ok {
		_spec.SetField(person.FieldActive, field.TypeBool, value)
	}
	if puo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.GroupTable,
			Columns: []string{person.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.GroupTable,
			Columns: []string{person.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.CheckoutsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedCheckoutsIDs(); len(nodes) > 0 && !puo.mutation.CheckoutsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.CheckoutsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.CheckoutsTable,
			Columns: []string{person.CheckoutsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkout.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Person{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{person.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
