// Code generated by ent, DO NOT EDIT.

package itemevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldKind, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldSummary, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldNote, v))
}

// ActorName applies equality check predicate on the "actor_name" field. It's identical to ActorNameEQ.
func ActorName(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldActorName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContainsFold(FieldKind, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContainsFold(FieldSummary, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContainsFold(FieldNote, v))
}

// ActorNameEQ applies the EQ predicate on the "actor_name" field.
func ActorNameEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEQ(FieldActorName, v))
}

// ActorNameNEQ applies the NEQ predicate on the "actor_name" field.
func ActorNameNEQ(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNEQ(FieldActorName, v))
}

// ActorNameIn applies the In predicate on the "actor_name" field.
func ActorNameIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIn(FieldActorName, vs...))
}

// ActorNameNotIn applies the NotIn predicate on the "actor_name" field.
func ActorNameNotIn(vs ...string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotIn(FieldActorName, vs...))
}

// ActorNameGT applies the GT predicate on the "actor_name" field.
func ActorNameGT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGT(FieldActorName, v))
}

// ActorNameGTE applies the GTE predicate on the "actor_name" field.
func ActorNameGTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldGTE(FieldActorName, v))
}

// ActorNameLT applies the LT predicate on the "actor_name" field.
func ActorNameLT(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLT(FieldActorName, v))
}

// ActorNameLTE applies the LTE predicate on the "actor_name" field.
func ActorNameLTE(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldLTE(FieldActorName, v))
}

// ActorNameContains applies the Contains predicate on the "actor_name" field.
func ActorNameContains(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContains(FieldActorName, v))
}

// ActorNameHasPrefix applies the HasPrefix predicate on the "actor_name" field.
func ActorNameHasPrefix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasPrefix(FieldActorName, v))
}

// ActorNameHasSuffix applies the HasSuffix predicate on the "actor_name" field.
func ActorNameHasSuffix(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldHasSuffix(FieldActorName, v))
}

// ActorNameIsNil applies the IsNil predicate on the "actor_name" field.
func ActorNameIsNil() predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldIsNull(FieldActorName))
}

// ActorNameNotNil applies the NotNil predicate on the "actor_name" field.
func ActorNameNotNil() predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldNotNull(FieldActorName))
}

// ActorNameEqualFold applies the EqualFold predicate on the "actor_name" field.
func ActorNameEqualFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldEqualFold(FieldActorName, v))
}

// ActorNameContainsFold applies the ContainsFold predicate on the "actor_name" field.
func ActorNameContainsFold(v string) predicate.ItemEvent {
	return predicate.ItemEvent(sql.FieldContainsFold(FieldActorName, v))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.ItemEvent {
	return predicate.ItemEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.ItemEvent {
	return predicate.ItemEvent(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemEvent) predicate.ItemEvent {
	return predicate.ItemEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemEvent) predicate.ItemEvent {
	return predicate.ItemEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemEvent) predicate.ItemEvent {
	return predicate.ItemEvent(sql.NotPredicates(p))
}
