// Code generated by ent, DO NOT EDIT.

package checkout

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the checkout type in the database.
	Label = "checkout"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCheckedOutAt holds the string denoting the checked_out_at field in the database.
	FieldCheckedOutAt = "checked_out_at"
	// FieldDueAt holds the string denoting the due_at field in the database.
	FieldDueAt = "due_at"
	// FieldReturnedAt holds the string denoting the returned_at field in the database.
	FieldReturnedAt = "returned_at"
	// FieldConditionOut holds the string denoting the condition_out field in the database.
	FieldConditionOut = "condition_out"
	// FieldConditionIn holds the string denoting the condition_in field in the database.
	FieldConditionIn = "condition_in"
	// FieldCheckoutNote holds the string denoting the checkout_note field in the database.
	FieldCheckoutNote = "checkout_note"
	// FieldReturnNote holds the string denoting the return_note field in the database.
	FieldReturnNote = "return_note"
	// FieldCheckedOutBy holds the string denoting the checked_out_by field in the database.
	FieldCheckedOutBy = "checked_out_by"
	// FieldReturnedBy holds the string denoting the returned_by field in the database.
	FieldReturnedBy = "returned_by"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// EdgePerson holds the string denoting the person edge name in mutations.
	EdgePerson = "person"
	// Table holds the table name of the checkout in the database.
	Table = "checkouts"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "checkouts"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_checkouts"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "checkouts"
	// ItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	ItemInverseTable = "items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "item_checkouts"
	// PersonTable is the table that holds the person relation/edge.
	PersonTable = "checkouts"
	// PersonInverseTable is the table name for the Person entity.
	// It exists in this package in order to avoid circular dependency with the "person" package.
	PersonInverseTable = "persons"
	// PersonColumn is the table column denoting the person relation/edge.
	PersonColumn = "person_checkouts"
)

// Columns holds all SQL columns for checkout fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCheckedOutAt,
	FieldDueAt,
	FieldReturnedAt,
	FieldConditionOut,
	FieldConditionIn,
	FieldCheckoutNote,
	FieldReturnNote,
	FieldCheckedOutBy,
	FieldReturnedBy,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "checkouts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"group_checkouts",
	"item_checkouts",
	"person_checkouts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCheckedOutAt holds the default value on creation for the "checked_out_at" field.
	DefaultCheckedOutAt func() time.Time
	// CheckoutNoteValidator is a validator for the "checkout_note" field. It is called by the builders before save.
	CheckoutNoteValidator func(string) error
	// ReturnNoteValidator is a validator for the "return_note" field. It is called by the builders before save.
	ReturnNoteValidator func(string) error
	// CheckedOutByValidator is a validator for the "checked_out_by" field. It is called by the builders before save.
	CheckedOutByValidator func(string) error
	// ReturnedByValidator is a validator for the "returned_by" field. It is called by the builders before save.
	ReturnedByValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ConditionOut defines the type for the "condition_out" enum field.
type ConditionOut string

// ConditionOutUnknown is the default value of the ConditionOut enum.
const DefaultConditionOut = ConditionOutUnknown

// ConditionOut values.
const (
	ConditionOutUnknown   ConditionOut = "unknown"
	ConditionOutExcellent ConditionOut = "excellent"
	ConditionOutGood      ConditionOut = "good"
	ConditionOutFair      ConditionOut = "fair"
	ConditionOutPoor      ConditionOut = "poor"
	ConditionOutDamaged   ConditionOut = "damaged"
)

func (co ConditionOut) String() string {
	return string(co)
}

// ConditionOutValidator is a validator for the "condition_out" field enum values. It is called by the builders before save.
func ConditionOutValidator(co ConditionOut) error {
	switch co {
	case ConditionOutUnknown, ConditionOutExcellent, ConditionOutGood, ConditionOutFair, ConditionOutPoor, ConditionOutDamaged:
		return nil
	default:
		return fmt.Errorf("checkout: invalid enum value for condition_out field: %q", co)
	}
}

// ConditionIn defines the type for the "condition_in" enum field.
type ConditionIn string

// ConditionInUnknown is the default value of the ConditionIn enum.
const DefaultConditionIn = ConditionInUnknown

// ConditionIn values.
const (
	ConditionInUnknown   ConditionIn = "unknown"
	ConditionInExcellent ConditionIn = "excellent"
	ConditionInGood      ConditionIn = "good"
	ConditionInFair      ConditionIn = "fair"
	ConditionInPoor      ConditionIn = "poor"
	ConditionInDamaged   ConditionIn = "damaged"
)

func (ci ConditionIn) String() string {
	return string(ci)
}

// ConditionInValidator is a validator for the "condition_in" field enum values. It is called by the builders before save.
func ConditionInValidator(ci ConditionIn) error {
	switch ci {
	case ConditionInUnknown, ConditionInExcellent, ConditionInGood, ConditionInFair, ConditionInPoor, ConditionInDamaged:
		return nil
	default:
		return fmt.Errorf("checkout: invalid enum value for condition_in field: %q", ci)
	}
}

// OrderOption defines the ordering options for the Checkout queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCheckedOutAt orders the results by the checked_out_at field.
func ByCheckedOutAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedOutAt, opts...).ToFunc()
}

// ByDueAt orders the results by the due_at field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByReturnedAt orders the results by the returned_at field.
func ByReturnedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnedAt, opts...).ToFunc()
}

// ByConditionOut orders the results by the condition_out field.
func ByConditionOut(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConditionOut, opts...).ToFunc()
}

// ByConditionIn orders the results by the condition_in field.
func ByConditionIn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConditionIn, opts...).ToFunc()
}

// ByCheckoutNote orders the results by the checkout_note field.
func ByCheckoutNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckoutNote, opts...).ToFunc()
}

// ByReturnNote orders the results by the return_note field.
func ByReturnNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnNote, opts...).ToFunc()
}

// ByCheckedOutBy orders the results by the checked_out_by field.
func ByCheckedOutBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedOutBy, opts...).ToFunc()
}

// ByReturnedBy orders the results by the returned_by field.
func ByReturnedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnedBy, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByItemField orders the results by item field.
func ByItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByPersonField orders the results by person field.
func ByPersonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPersonStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
	)
}
func newPersonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PersonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PersonTable, PersonColumn),
	)
}
