// Code generated by ent, DO NOT EDIT.

package checkout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedAt, v))
}

// CheckedOutAt applies equality check predicate on the "checked_out_at" field. It's identical to CheckedOutAtEQ.
func CheckedOutAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckedOutAt, v))
}

// DueAt applies equality check predicate on the "due_at" field. It's identical to DueAtEQ.
func DueAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldDueAt, v))
}

// ReturnedAt applies equality check predicate on the "returned_at" field. It's identical to ReturnedAtEQ.
func ReturnedAt(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnedAt, v))
}

// CheckoutNote applies equality check predicate on the "checkout_note" field. It's identical to CheckoutNoteEQ.
func CheckoutNote(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutNote, v))
}

// ReturnNote applies equality check predicate on the "return_note" field. It's identical to ReturnNoteEQ.
func ReturnNote(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnNote, v))
}

// CheckedOutBy applies equality check predicate on the "checked_out_by" field. It's identical to CheckedOutByEQ.
func CheckedOutBy(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckedOutBy, v))
}

// ReturnedBy applies equality check predicate on the "returned_by" field. It's identical to ReturnedByEQ.
func ReturnedBy(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldUpdatedAt, v))
}

// CheckedOutAtEQ applies the EQ predicate on the "checked_out_at" field.
func CheckedOutAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckedOutAt, v))
}

// CheckedOutAtNEQ applies the NEQ predicate on the "checked_out_at" field.
func CheckedOutAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCheckedOutAt, v))
}

// CheckedOutAtIn applies the In predicate on the "checked_out_at" field.
func CheckedOutAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCheckedOutAt, vs...))
}

// CheckedOutAtNotIn applies the NotIn predicate on the "checked_out_at" field.
func CheckedOutAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCheckedOutAt, vs...))
}

// CheckedOutAtGT applies the GT predicate on the "checked_out_at" field.
func CheckedOutAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCheckedOutAt, v))
}

// CheckedOutAtGTE applies the GTE predicate on the "checked_out_at" field.
func CheckedOutAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCheckedOutAt, v))
}

// CheckedOutAtLT applies the LT predicate on the "checked_out_at" field.
func CheckedOutAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCheckedOutAt, v))
}

// CheckedOutAtLTE applies the LTE predicate on the "checked_out_at" field.
func CheckedOutAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCheckedOutAt, v))
}

// DueAtEQ applies the EQ predicate on the "due_at" field.
func DueAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldDueAt, v))
}

// DueAtNEQ applies the NEQ predicate on the "due_at" field.
func DueAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldDueAt, v))
}

// DueAtIn applies the In predicate on the "due_at" field.
func DueAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldDueAt, vs...))
}

// DueAtNotIn applies the NotIn predicate on the "due_at" field.
func DueAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldDueAt, vs...))
}

// DueAtGT applies the GT predicate on the "due_at" field.
func DueAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldDueAt, v))
}

// DueAtGTE applies the GTE predicate on the "due_at" field.
func DueAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldDueAt, v))
}

// DueAtLT applies the LT predicate on the "due_at" field.
func DueAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldDueAt, v))
}

// DueAtLTE applies the LTE predicate on the "due_at" field.
func DueAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldDueAt, v))
}

// DueAtIsNil applies the IsNil predicate on the "due_at" field.
func DueAtIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldDueAt))
}

// DueAtNotNil applies the NotNil predicate on the "due_at" field.
func DueAtNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldDueAt))
}

// ReturnedAtEQ applies the EQ predicate on the "returned_at" field.
func ReturnedAtEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnedAt, v))
}

// ReturnedAtNEQ applies the NEQ predicate on the "returned_at" field.
func ReturnedAtNEQ(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldReturnedAt, v))
}

// ReturnedAtIn applies the In predicate on the "returned_at" field.
func ReturnedAtIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldReturnedAt, vs...))
}

// ReturnedAtNotIn applies the NotIn predicate on the "returned_at" field.
func ReturnedAtNotIn(vs ...time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldReturnedAt, vs...))
}

// ReturnedAtGT applies the GT predicate on the "returned_at" field.
func ReturnedAtGT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldReturnedAt, v))
}

// ReturnedAtGTE applies the GTE predicate on the "returned_at" field.
func ReturnedAtGTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldReturnedAt, v))
}

// ReturnedAtLT applies the LT predicate on the "returned_at" field.
func ReturnedAtLT(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldReturnedAt, v))
}

// ReturnedAtLTE applies the LTE predicate on the "returned_at" field.
func ReturnedAtLTE(v time.Time) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldReturnedAt, v))
}

// ReturnedAtIsNil applies the IsNil predicate on the "returned_at" field.
func ReturnedAtIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldReturnedAt))
}

// ReturnedAtNotNil applies the NotNil predicate on the "returned_at" field.
func ReturnedAtNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldReturnedAt))
}

// ConditionOutEQ applies the EQ predicate on the "condition_out" field.
func ConditionOutEQ(v ConditionOut) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldConditionOut, v))
}

// ConditionOutNEQ applies the NEQ predicate on the "condition_out" field.
func ConditionOutNEQ(v ConditionOut) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldConditionOut, v))
}

// ConditionOutIn applies the In predicate on the "condition_out" field.
func ConditionOutIn(vs ...ConditionOut) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldConditionOut, vs...))
}

// ConditionOutNotIn applies the NotIn predicate on the "condition_out" field.
func ConditionOutNotIn(vs ...ConditionOut) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldConditionOut, vs...))
}

// ConditionInEQ applies the EQ predicate on the "condition_in" field.
func ConditionInEQ(v ConditionIn) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldConditionIn, v))
}

// ConditionInNEQ applies the NEQ predicate on the "condition_in" field.
func ConditionInNEQ(v ConditionIn) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldConditionIn, v))
}

// ConditionInIn applies the In predicate on the "condition_in" field.
func ConditionInIn(vs ...ConditionIn) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldConditionIn, vs...))
}

// ConditionInNotIn applies the NotIn predicate on the "condition_in" field.
func ConditionInNotIn(vs ...ConditionIn) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldConditionIn, vs...))
}

// CheckoutNoteEQ applies the EQ predicate on the "checkout_note" field.
func CheckoutNoteEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckoutNote, v))
}

// CheckoutNoteNEQ applies the NEQ predicate on the "checkout_note" field.
func CheckoutNoteNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCheckoutNote, v))
}

// CheckoutNoteIn applies the In predicate on the "checkout_note" field.
func CheckoutNoteIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCheckoutNote, vs...))
}

// CheckoutNoteNotIn applies the NotIn predicate on the "checkout_note" field.
func CheckoutNoteNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCheckoutNote, vs...))
}

// CheckoutNoteGT applies the GT predicate on the "checkout_note" field.
func CheckoutNoteGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCheckoutNote, v))
}

// CheckoutNoteGTE applies the GTE predicate on the "checkout_note" field.
func CheckoutNoteGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCheckoutNote, v))
}

// CheckoutNoteLT applies the LT predicate on the "checkout_note" field.
func CheckoutNoteLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCheckoutNote, v))
}

// CheckoutNoteLTE applies the LTE predicate on the "checkout_note" field.
func CheckoutNoteLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCheckoutNote, v))
}

// CheckoutNoteContains applies the Contains predicate on the "checkout_note" field.
func CheckoutNoteContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCheckoutNote, v))
}

// CheckoutNoteHasPrefix applies the HasPrefix predicate on the "checkout_note" field.
func CheckoutNoteHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCheckoutNote, v))
}

// CheckoutNoteHasSuffix applies the HasSuffix predicate on the "checkout_note" field.
func CheckoutNoteHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCheckoutNote, v))
}

// CheckoutNoteIsNil applies the IsNil predicate on the "checkout_note" field.
func CheckoutNoteIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCheckoutNote))
}

// CheckoutNoteNotNil applies the NotNil predicate on the "checkout_note" field.
func CheckoutNoteNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCheckoutNote))
}

// CheckoutNoteEqualFold applies the EqualFold predicate on the "checkout_note" field.
func CheckoutNoteEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCheckoutNote, v))
}

// CheckoutNoteContainsFold applies the ContainsFold predicate on the "checkout_note" field.
func CheckoutNoteContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCheckoutNote, v))
}

// ReturnNoteEQ applies the EQ predicate on the "return_note" field.
func ReturnNoteEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnNote, v))
}

// ReturnNoteNEQ applies the NEQ predicate on the "return_note" field.
func ReturnNoteNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldReturnNote, v))
}

// ReturnNoteIn applies the In predicate on the "return_note" field.
func ReturnNoteIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldReturnNote, vs...))
}

// ReturnNoteNotIn applies the NotIn predicate on the "return_note" field.
func ReturnNoteNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldReturnNote, vs...))
}

// ReturnNoteGT applies the GT predicate on the "return_note" field.
func ReturnNoteGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldReturnNote, v))
}

// ReturnNoteGTE applies the GTE predicate on the "return_note" field.
func ReturnNoteGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldReturnNote, v))
}

// ReturnNoteLT applies the LT predicate on the "return_note" field.
func ReturnNoteLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldReturnNote, v))
}

// ReturnNoteLTE applies the LTE predicate on the "return_note" field.
func ReturnNoteLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldReturnNote, v))
}

// ReturnNoteContains applies the Contains predicate on the "return_note" field.
func ReturnNoteContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldReturnNote, v))
}

// ReturnNoteHasPrefix applies the HasPrefix predicate on the "return_note" field.
func ReturnNoteHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldReturnNote, v))
}

// ReturnNoteHasSuffix applies the HasSuffix predicate on the "return_note" field.
func ReturnNoteHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldReturnNote, v))
}

// ReturnNoteIsNil applies the IsNil predicate on the "return_note" field.
func ReturnNoteIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldReturnNote))
}

// ReturnNoteNotNil applies the NotNil predicate on the "return_note" field.
func ReturnNoteNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldReturnNote))
}

// ReturnNoteEqualFold applies the EqualFold predicate on the "return_note" field.
func ReturnNoteEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldReturnNote, v))
}

// ReturnNoteContainsFold applies the ContainsFold predicate on the "return_note" field.
func ReturnNoteContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldReturnNote, v))
}

// CheckedOutByEQ applies the EQ predicate on the "checked_out_by" field.
func CheckedOutByEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldCheckedOutBy, v))
}

// CheckedOutByNEQ applies the NEQ predicate on the "checked_out_by" field.
func CheckedOutByNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldCheckedOutBy, v))
}

// CheckedOutByIn applies the In predicate on the "checked_out_by" field.
func CheckedOutByIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldCheckedOutBy, vs...))
}

// CheckedOutByNotIn applies the NotIn predicate on the "checked_out_by" field.
func CheckedOutByNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldCheckedOutBy, vs...))
}

// CheckedOutByGT applies the GT predicate on the "checked_out_by" field.
func CheckedOutByGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldCheckedOutBy, v))
}

// CheckedOutByGTE applies the GTE predicate on the "checked_out_by" field.
func CheckedOutByGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldCheckedOutBy, v))
}

// CheckedOutByLT applies the LT predicate on the "checked_out_by" field.
func CheckedOutByLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldCheckedOutBy, v))
}

// CheckedOutByLTE applies the LTE predicate on the "checked_out_by" field.
func CheckedOutByLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldCheckedOutBy, v))
}

// CheckedOutByContains applies the Contains predicate on the "checked_out_by" field.
func CheckedOutByContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldCheckedOutBy, v))
}

// CheckedOutByHasPrefix applies the HasPrefix predicate on the "checked_out_by" field.
func CheckedOutByHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldCheckedOutBy, v))
}

// CheckedOutByHasSuffix applies the HasSuffix predicate on the "checked_out_by" field.
func CheckedOutByHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldCheckedOutBy, v))
}

// CheckedOutByIsNil applies the IsNil predicate on the "checked_out_by" field.
func CheckedOutByIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldCheckedOutBy))
}

// CheckedOutByNotNil applies the NotNil predicate on the "checked_out_by" field.
func CheckedOutByNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldCheckedOutBy))
}

// CheckedOutByEqualFold applies the EqualFold predicate on the "checked_out_by" field.
func CheckedOutByEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldCheckedOutBy, v))
}

// CheckedOutByContainsFold applies the ContainsFold predicate on the "checked_out_by" field.
func CheckedOutByContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldCheckedOutBy, v))
}

// ReturnedByEQ applies the EQ predicate on the "returned_by" field.
func ReturnedByEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEQ(FieldReturnedBy, v))
}

// ReturnedByNEQ applies the NEQ predicate on the "returned_by" field.
func ReturnedByNEQ(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNEQ(FieldReturnedBy, v))
}

// ReturnedByIn applies the In predicate on the "returned_by" field.
func ReturnedByIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldIn(FieldReturnedBy, vs...))
}

// ReturnedByNotIn applies the NotIn predicate on the "returned_by" field.
func ReturnedByNotIn(vs ...string) predicate.Checkout {
	return predicate.Checkout(sql.FieldNotIn(FieldReturnedBy, vs...))
}

// ReturnedByGT applies the GT predicate on the "returned_by" field.
func ReturnedByGT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGT(FieldReturnedBy, v))
}

// ReturnedByGTE applies the GTE predicate on the "returned_by" field.
func ReturnedByGTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldGTE(FieldReturnedBy, v))
}

// ReturnedByLT applies the LT predicate on the "returned_by" field.
func ReturnedByLT(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLT(FieldReturnedBy, v))
}

// ReturnedByLTE applies the LTE predicate on the "returned_by" field.
func ReturnedByLTE(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldLTE(FieldReturnedBy, v))
}

// ReturnedByContains applies the Contains predicate on the "returned_by" field.
func ReturnedByContains(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContains(FieldReturnedBy, v))
}

// ReturnedByHasPrefix applies the HasPrefix predicate on the "returned_by" field.
func ReturnedByHasPrefix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasPrefix(FieldReturnedBy, v))
}

// ReturnedByHasSuffix applies the HasSuffix predicate on the "returned_by" field.
func ReturnedByHasSuffix(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldHasSuffix(FieldReturnedBy, v))
}

// ReturnedByIsNil applies the IsNil predicate on the "returned_by" field.
func ReturnedByIsNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldIsNull(FieldReturnedBy))
}

// ReturnedByNotNil applies the NotNil predicate on the "returned_by" field.
func ReturnedByNotNil() predicate.Checkout {
	return predicate.Checkout(sql.FieldNotNull(FieldReturnedBy))
}

// ReturnedByEqualFold applies the EqualFold predicate on the "returned_by" field.
func ReturnedByEqualFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldEqualFold(FieldReturnedBy, v))
}

// ReturnedByContainsFold applies the ContainsFold predicate on the "returned_by" field.
func ReturnedByContainsFold(v string) predicate.Checkout {
	return predicate.Checkout(sql.FieldContainsFold(FieldReturnedBy, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPerson applies the HasEdge predicate on the "person" edge.
func HasPerson() predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PersonTable, PersonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonWith applies the HasEdge predicate on the "person" edge with a given conditions (other predicates).
func HasPersonWith(preds ...predicate.Person) predicate.Checkout {
	return predicate.Checkout(func(s *sql.Selector) {
		step := newPersonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Checkout) predicate.Checkout {
	return predicate.Checkout(sql.NotPredicates(p))
}
