// Code generated by ent, DO NOT EDIT.

package itemtag

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sdmad737/catalog/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicToken applies equality check predicate on the "public_token" field. It's identical to PublicTokenEQ.
func PublicToken(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldPublicToken, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldRevokedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldVerifiedAt, v))
}

// LastScannedAt applies equality check predicate on the "last_scanned_at" field. It's identical to LastScannedAtEQ.
func LastScannedAt(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldLastScannedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldUpdatedAt, v))
}

// PublicTokenEQ applies the EQ predicate on the "public_token" field.
func PublicTokenEQ(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldPublicToken, v))
}

// PublicTokenNEQ applies the NEQ predicate on the "public_token" field.
func PublicTokenNEQ(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldPublicToken, v))
}

// PublicTokenIn applies the In predicate on the "public_token" field.
func PublicTokenIn(vs ...string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldPublicToken, vs...))
}

// PublicTokenNotIn applies the NotIn predicate on the "public_token" field.
func PublicTokenNotIn(vs ...string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldPublicToken, vs...))
}

// PublicTokenGT applies the GT predicate on the "public_token" field.
func PublicTokenGT(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldPublicToken, v))
}

// PublicTokenGTE applies the GTE predicate on the "public_token" field.
func PublicTokenGTE(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldPublicToken, v))
}

// PublicTokenLT applies the LT predicate on the "public_token" field.
func PublicTokenLT(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldPublicToken, v))
}

// PublicTokenLTE applies the LTE predicate on the "public_token" field.
func PublicTokenLTE(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldPublicToken, v))
}

// PublicTokenContains applies the Contains predicate on the "public_token" field.
func PublicTokenContains(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldContains(FieldPublicToken, v))
}

// PublicTokenHasPrefix applies the HasPrefix predicate on the "public_token" field.
func PublicTokenHasPrefix(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldHasPrefix(FieldPublicToken, v))
}

// PublicTokenHasSuffix applies the HasSuffix predicate on the "public_token" field.
func PublicTokenHasSuffix(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldHasSuffix(FieldPublicToken, v))
}

// PublicTokenEqualFold applies the EqualFold predicate on the "public_token" field.
func PublicTokenEqualFold(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEqualFold(FieldPublicToken, v))
}

// PublicTokenContainsFold applies the ContainsFold predicate on the "public_token" field.
func PublicTokenContainsFold(v string) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldContainsFold(FieldPublicToken, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotNull(FieldRevokedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotNull(FieldVerifiedAt))
}

// LastScannedAtEQ applies the EQ predicate on the "last_scanned_at" field.
func LastScannedAtEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldEQ(FieldLastScannedAt, v))
}

// LastScannedAtNEQ applies the NEQ predicate on the "last_scanned_at" field.
func LastScannedAtNEQ(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNEQ(FieldLastScannedAt, v))
}

// LastScannedAtIn applies the In predicate on the "last_scanned_at" field.
func LastScannedAtIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIn(FieldLastScannedAt, vs...))
}

// LastScannedAtNotIn applies the NotIn predicate on the "last_scanned_at" field.
func LastScannedAtNotIn(vs ...time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotIn(FieldLastScannedAt, vs...))
}

// LastScannedAtGT applies the GT predicate on the "last_scanned_at" field.
func LastScannedAtGT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGT(FieldLastScannedAt, v))
}

// LastScannedAtGTE applies the GTE predicate on the "last_scanned_at" field.
func LastScannedAtGTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldGTE(FieldLastScannedAt, v))
}

// LastScannedAtLT applies the LT predicate on the "last_scanned_at" field.
func LastScannedAtLT(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLT(FieldLastScannedAt, v))
}

// LastScannedAtLTE applies the LTE predicate on the "last_scanned_at" field.
func LastScannedAtLTE(v time.Time) predicate.ItemTag {
	return predicate.ItemTag(sql.FieldLTE(FieldLastScannedAt, v))
}

// LastScannedAtIsNil applies the IsNil predicate on the "last_scanned_at" field.
func LastScannedAtIsNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldIsNull(FieldLastScannedAt))
}

// LastScannedAtNotNil applies the NotNil predicate on the "last_scanned_at" field.
func LastScannedAtNotNil() predicate.ItemTag {
	return predicate.ItemTag(sql.FieldNotNull(FieldLastScannedAt))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.ItemTag {
	return predicate.ItemTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.Item) predicate.ItemTag {
	return predicate.ItemTag(func(s *sql.Selector) {
		step := newItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemTag) predicate.ItemTag {
	return predicate.ItemTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemTag) predicate.ItemTag {
	return predicate.ItemTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemTag) predicate.ItemTag {
	return predicate.ItemTag(sql.NotPredicates(p))
}
